### PR TITLE
[13.0][IMP] partner_statement

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
- Added support for html and xlsx report for activity and outgoing statement
- Support for multi-currency

### CODE REVIEW

**Comment by ChrisOForgeFlow** [comment]
@ForgeFlow

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Functional review. Works like a charm!

**Review by HaraldPanten — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@ChrisOForgeFlow Could you forward port this to v14?

**Pull request merged**
