### PR TITLE
[IMP] Performance fix on last_rec_date initialization

### PR DESCRIPTION
**Pull request by pablocm-aserti**

### CODE REVIEW

**Comment by sbidoul** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Hi, Pablo, thanks for the PR.

Please correct line length (it's 79, not 80):

```
./account_financial_report_webkit/migrations/7.0.1.0.2/post-migration.py:31:80: E501 line too long (80 > 79 characters)
./account_financial_report_webkit/migrations/7.0.1.0.2/post-migration.py:39:80: E501 line too long (88 > 79 characters)
```

**Comment by StefanRijnhart** [comment]
Thanks! :+1:. As you have addressed Pedro's concerns, I will proceed with the merge.

**Comment by pablocm-aserti** [comment]
Thank you Stefan!

**Comment by pedrobaeza** [comment]
Pablo, next time, please write here a comment to know that you have made the changes. BTW, merge is done :wink:

**Comment by pablocm-aserti** [comment]
Sorry, I thought it was enough with the travis' OK. I'll keep that in mind for the next time, thanks!

**Pull request merged**
