### PR TITLE
[10.0][FIX] account_financial_report: Extremely auto vaccum query execute to delete report_journal_ledger table

### PR DESCRIPTION
**Pull request by sergio-teruel**
Backport of #582

cc @Tecnativa

### CODE REVIEW

**Comment by sbidoul** [comment]
I made the same in #573.

But I think if the only benefit is the autovacuum performance, then it's better to delete the report move lines in a a first step before deleting the moves, so we don't rely on the cascading delete.
This way we don't have the performance hit of maintaining an index that is otherwise useless.

**Comment by pedrobaeza** [comment]
@sbidoul Isn't the query `DELETE FROM .. WHERE report_id = X` will be the same slow as DELETE CASCADE without the index?

**Comment by sbidoul** [comment]
@pedrobaeza I'm not sure. The delete of the move needs to search the related move lines to cascade the delete, then the index is needed. If we delete the lines first and don't do a cascade from the moves, then there is no need to search move lines by move id and the index is not necessary. I've not tested.

**Comment by rafaelbn** [comment]
Functionaly this works so :+1: 

If @sbidoul did the same in https://github.com/OCA/account-financial-reporting/pull/573 we can merge that one then

**Review by rafaelbn — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Closing as we will cherry-pick #582

**Pull request closed without merging**
