### PR TITLE
[FIX] check if the line have an amount currency instead of the linked…

### PR DESCRIPTION
**Pull request by vrenaville**
I check if the line have a amount currency instead of the currency of the linked account.

### CODE REVIEW

**Comment by vrenaville** [comment]
If you create invoice in company currency and foreign currency on the same account, you will not be able to print the currency balance.

**Comment by pedrobaeza** [comment]
Isn't needed to fallback to the currency of the account?

**Comment by vrenaville** [comment]
@luc-demeyer Could you please review this PR
thanks for your help

**Comment by vrenaville** [comment]
@pedrobaeza I don't think it's necessary,(but I can be wrong :) ) if you specified a currency on a account all the related move line must have the fields currency and amount_currency set.

**Comment by pedrobaeza** [comment]
OK, I think so also

:+1:

**Comment by max3903** [comment]
:+1:

**Comment by luc-demeyer** [comment]
@vrenaville 
Thanks for correcting this bug.
:+1: 
I think this PR is ready for merge.

**Pull request merged**
