### PR TITLE
[14.0][FIX] account_tax_balance: Recompute balance for different dates

### PR DESCRIPTION
**Pull request by SimoRubi**
See added test, I haven't found a way to reproduce this issue from the UI using only this module.

### CODE REVIEW

**Comment by tafaRU** [comment]
@SimoRubi you could rebase in order to include https://github.com/OCA/account-financial-reporting/pull/838

**Review by tafaRU — APPROVED** [review]

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers can this be merged? Thanks

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by AaronHForgeFlow** [comment]
@SimoRubi can you please forward fort this to 15.0?

**Comment by SimoRubi** [comment]
> @SimoRubi can you please forward fort this to 15.0?

Thanks for the review!
Done in https://github.com/OCA/account-financial-reporting/pull/854

**Pull request merged**
