### PR TITLE
[14.0][mis_builder_cash_flow] mig mis_builder_cash_flow

### PR DESCRIPTION
**Pull request by rvalyi**
An newer version of https://github.com/OCA/account-financial-reporting/pull/768 with:

* the latest v13.0 changes from Tecnativa https://github.com/OCA/account-financial-reporting/pull/802
* a fix for the offending mis_cash_flow_search_view of #768: assuming the balance filter never worked I simply removed it. In the future one could bother ensuring debit and credit are not null, but as worked without such filter so far I preferred drop the offending balance filter.
* a fix to make tests pass: type -> move_type for the account.move object.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
If presumably goes green in Travis

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request merged**
