### PR TITLE
[16.0][MIG] account_tax_balance: Migration to 16.0 

### PR DESCRIPTION
**Pull request by ramiadavid**

### CODE REVIEW

**Comment by ramiadavid** [comment]
Hi @pedrobaeza 
The tests are fine, but I'm not 100% sure if the change from internal_type to account_type is correct, if you can check it.
Thank you

**Review by tafaRU — CHANGES_REQUESTED** [review]
Overall LGTM except for https://github.com/ramiadavid/account-financial-reporting/pull/1
--edit--: please also squash administrative commits (if any) with the previous commit for reducing commit noise.

Thanks a lot!

**Review by eLBati — APPROVED** [review]
Tested

**Comment by tafaRU** [comment]
@ramiadavid thanks for merging my PR! Please also squash administrative commits, then your PR is ready for the merge :+1:

**Comment by tafaRU** [comment]
@ramiadavid let me know if you need help for merging the squash administrative commits.

**Comment by pedrobaeza** [comment]
I'm improving the guide for this. I'm pasting the link when finish.

**Comment by ramiadavid** [comment]
> @ramiadavid let me know if you need help for merging the squash administrative commits.


If you can explain me how to do it correctly, I would appreciate it, because I don't want to do it wrong

**Comment by pedrobaeza** [comment]
Uf, it has taken more time than expected, but I hope they are good enough:

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

Please tell any suggestion to it.

**Comment by ramiadavid** [comment]
@tafaRU @pedrobaeza  I think it is ready

**Comment by tafaRU** [comment]
@ramiadavid you missed one:

image

**Comment by pedrobaeza** [comment]
I think that one of the cases where a conflict arises.

**Comment by ramiadavid** [comment]
@tafaRU I'm not sure how to do this, since it causes a conflict

**Comment by pedrobaeza** [comment]
@tafaRU can you please update your review?

**Review by tafaRU — APPROVED** [review]

**Comment by Gelo-fl** [comment]
Hi @dreispt,

This module is merged, however the translations are locked:
[account-financial-reporting-16.0-account_tax_balance](https://translation.odoo-community.org/projects/account-financial-reporting-16-0/account-financial-reporting-16-0-account_tax_balance/)
Can I know why?

Thanks in advance,

**Comment by pedrobaeza** [comment]
Unlocked.

**Pull request merged**
