### PR TITLE
[11.0][FIX] account_financial_report: singleton error in aged partner balance report

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
I think this PR solves https://github.com/OCA/account-financial-reporting/issues/513.

### CODE REVIEW

**Comment by astirpe** [comment]
Hi @mreficent 

Now it gives this error:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_move_lines_113
  File "<template>", line 46, in foreach_112
AttributeError: 'list' object has no attribute 'extends'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/account_financial_report/report/aged_partner_balance.py", line 214, in get_html
    return self._get_html()
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/account_financial_report/report/aged_partner_balance.py", line 209, in _get_html
    rcontext)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 1217, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1696_58
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_base_88
  File "<template>", line 14, in foreach_87
  File "<template>", line 45, in foreach_84
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 350, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'list' object has no attribute 'extends'
Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_move_lines_113
  File "<template>", line 46, in foreach_112
AttributeError: 'list' object has no attribute 'extends'

Error to render compiling AST
AttributeError: 'list' object has no attribute 'extends'
Template: account_financial_report.report_aged_partner_balance_move_lines
Path: /templates/t/div/t/div/div[8]/span/a
Node: <a t-att-data-domain="[('id', 'in', [x for x in [line.move_line_id.id].extends(line.move_line_id.matched_debit_ids.mapped('debit_move_id').ids).extends(line.move_line_id.matched_credit_ids.mapped('credit_move_id').ids) if x != False])]" t-att-data-res-model="'account.move.line'" class="o_account_financial_reports_web_action_multi" style="color: black;">
                            <t t-raw="line.amount_residual" t-options="{'widget': 'monetary', 'display_currency': res_company.currency_id}"/></a>

```

**Comment by MiquelRForgeFlow** [comment]
Sorry, it's `extend` instead of `extends` 😅

Fixed.

**Comment by astirpe** [comment]
Now it's this:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_move_lines_113
  File "<template>", line 46, in foreach_112
AttributeError: 'NoneType' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/account_financial_report/report/aged_partner_balance.py", line 214, in get_html
    return self._get_html()
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/oca/account_financial_report/report/aged_partner_balance.py", line 209, in _get_html
    rcontext)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_ui_view.py", line 1217, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1696_58
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_base_88
  File "<template>", line 14, in foreach_87
  File "<template>", line 45, in foreach_84
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 350, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'NoneType' object has no attribute 'extend'
Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_move_lines_113
  File "<template>", line 46, in foreach_112
AttributeError: 'NoneType' object has no attribute 'extend'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'extend'
Template: account_financial_report.report_aged_partner_balance_move_lines
Path: /templates/t/div/t/div/div[8]/span/a
Node: <a t-att-data-domain="[('id', 'in', [x for x in [line.move_line_id.id].extend(line.move_line_id.matched_debit_ids.mapped('debit_move_id').ids).extend(line.move_line_id.matched_credit_ids.mapped('credit_move_id').ids) if x])]" t-att-data-res-model="'account.move.line'" class="o_account_financial_reports_web_action_multi" style="color: black;">
                            <t t-raw="line.amount_residual" t-options="{'widget': 'monetary', 'display_currency': res_company.currency_id}"/></a>

```

**Comment by MiquelRForgeFlow** [comment]
Thanks. Fixed again!!

**Comment by astirpe** [comment]
Ok, the report is now generated.
But in the HTML report, when I click on the amount I get this:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/onestein/Pycharm/Gitlab/odoo-11.0/src/odoo-11.0/odoo/http.py", line 318, in _call_function
    raise werkzeug.exceptions.BadRequest(msg % params)
werkzeug.exceptions.BadRequest: 400 Bad Request: <function Home.web_client at 0x7f5f16c28a60>, /web: Function declared as capable of handling request of type 'http' but called with a request of type 'json'
```

**Comment by MiquelRForgeFlow** [comment]
But this last error is produced by this PR or it's another unrelated error?

**Comment by astirpe** [comment]
I just reproduced that error on a fresh database, in both cases: with your PR and without your PR.

The aged partner balance report without details (Show Move Line Details = False) doesn't have the hyperlink tags (the `<a>...</a>` tags). Instead the detailed aged partner balance (Show Move Line Details = True) has those tags.

I would rather remove the hyperlink tags, since they are not working at all. Do we really need them?

**Comment by MiquelRForgeFlow** [comment]
@astirpe The intention of this PR was to solve a specific issue. If this last error is unrelated with the issue, then could you approve it?

I don't really understand this last error from the server error excerpt you shown. Maybe it's something of odoo.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Code review

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza

**Pull request merged**
