### PR TITLE
[FIX] mis_builder: add web_widget_color dependency

### PR DESCRIPTION
**Pull request by sbidoul**
now that the dependency is merged in 9.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Mention in "Installation" section the dependency.

**Comment by sbidoul** [comment]
I added OCA/web to runbot. Everything green now.

@pedrobaeza other dependencies (date_range, report_xlsx) are not in the README either. Is that a convention we have to enumerate all dependencies in the README?

**Review by lmignon — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
Yeah, until pip will be the general method to install, we should write in installation section all dependencies of external repositories.

**Comment by sbidoul** [comment]
@pedrobaeza I don't find that written in the guidlines.

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
It's implicit in the README (installation section): https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst, but OK if you don't consider that.

**Comment by ThomasBinsfeld** [comment]
:+1:

**Pull request merged**
