### PR TITLE
[10.0] General ledger, foreign currency in initial and final balance

### PR DESCRIPTION
**Pull request by SimoRubi**
With this modifications, the General ledger shows foreign currency also for initial and final balance, only if all the lines summarized have foreign currency.
Please check, thanks

### CODE REVIEW

**Review by hurrinico — APPROVED** [review]
👍 imho

**Comment by JordiBForgeFlow** [comment]
@SimoRubi Should not it be better to express the balance in currency when the account has a secondary currency? As odoo already forces all the moves to be using this secondary currency. See https://github.com/odoo/odoo/blob/11.0/addons/account/models/account.py#L58

**Comment by SimoRubi** [comment]
Thanks @hurrinico for the review.

@jbeficent thanks I didn't think of that, it would sure be more efficient from the performance point of view; but the following use case wouldn't be covered: 
- account with no currency,
- moves in only one currency 

This might happen if you filter for a specific partner that has a currency for instance.

**Comment by JordiBForgeFlow** [comment]
@SimoRubi I have proposed this PR https://github.com/SimoRubi/account-financial-reporting/pull/1

In the general ledger the totals in foreign currency are only computed if the account has a secondary currency. Otherwise the move lines will still show the amount expressed in foreign currency, but it is assumed that the account could contain various moves in different currencies, and will not calculate the total in the foreign currency.

Adds the foreign currency initial and ending balance to the trial balance.

**Comment by JordiBForgeFlow** [comment]
@feketemihai I plan to cherry pick this PR (considering https://github.com/SimoRubi/account-financial-reporting/pull/1) to 11.0 once it is merged in 10.0

**Comment by feketemihai** [comment]
@jbeficent Ok, i will review when i have time.

**Comment by SimoRubi** [comment]
@jbeficent you (and others) managed to convince me that your way is better.
I've added the diff of your PR https://github.com/SimoRubi/account-financial-reporting/pull/1, I didn't merge it in my repo because it had strange commit history (in first commit you modified some code that was then deleted in second commit), hope it's ok for you now.

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by feketemihai — APPROVED** [review]
Not tested.

**Comment by feketemihai** [comment]
@jbeficent To be merged...

**Comment by JordiBForgeFlow** [comment]
Is the XLS also covered? @hveficent can you migrate this feature to v11?

**Comment by SimoRubi** [comment]
No @jbeficent I'm working on it and on open items report in https://github.com/OCA/account-financial-reporting/pull/407

**Pull request merged**
