### PR TITLE
[14.0][FIX] account_tax_balance hook

### PR DESCRIPTION
**Pull request by SimoneVagile**
Forward porting of [https://github.com/OCA/account-financial-reporting/pull/763](https://github.com/OCA/account-financial-reporting/pull/763)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why 3 commits?

**Comment by pedrobaeza** [comment]
And no need to manually bump version module

**Comment by pedrobaeza** [comment]
You should still leave it in one commit, doing the pre-commit stuff in the same commit.

**Comment by SimoneVagile** [comment]
@pedrobaeza thanks for quick reply:

- First commit was cherry-picked from [https://github.com/OCA/account-financial-reporting/pull/763/commits/598774c7cb0e57e5af087e28689b56a11fa6e1e1](https://github.com/OCA/account-financial-reporting/pull/763/commits/598774c7cb0e57e5af087e28689b56a11fa6e1e1)
- Second commit has been added to reintroduce `"` in variable `MAPPING`
- Third is a temporary bump for our internal use, has been removed :wink:

**Comment by pedrobaeza** [comment]
Not sure if you see my last message before putting the other thing.

**Comment by SimoneVagile** [comment]
@pedrobaeza sqaushed

**Comment by pedrobaeza** [comment]
Fast-tracking it:

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Cherry-picked for v13 at dd190e14e6bbf120a51c179cfba4771a3dfa07fd

**Pull request merged**
