### PR TITLE
[IMP][14.0][account_financial_report] Add landscape report option to Open Items

### PR DESCRIPTION
**Pull request by driehuis**
The Open Items report has a lot of information packed into one line. This pull request adds a landscape option to the report for legibility.

### CODE REVIEW

**Comment by driehuis** [comment]
I'll see if I can remove the -0.01% of code coverage introduced by this patch.

**Comment by driehuis** [comment]
Hmmm, seems like the actual report generation is not tested at all.

**Comment by driehuis** [comment]
Actually generating a report in the test has bumped code coverage for `open_items.py` from 7% to 53%, and ensured that all added code has been tested.

**Comment by driehuis** [comment]
Even more test coverage for `open_items.py`. Still no 100% line coverage, but at least all functions seem to be hit by a test now (and because open_items.py deals with a lot of corner cases, a metric buttload of code is needed to reach 100% coverage). Anyway, I'm unlikely to further improve test coverage for this module in the short term.

**Comment by driehuis** [comment]
Frustratingly, these tests worked for me on my system... I'll hunt for the regression and fix it.

**Review by tafaRU — APPROVED** [review]

**Comment by tafaRU** [comment]
@OCA/accounting-maintainers this PR is ready to be merged, anyone else want to review it? If not I proceed with the merge considering the module `development_status` is Beta.

**Comment by rafaelbn** [comment]
Please @driehuis could add some screenshot or mini-video? 🙏

**Comment by tafaRU** [comment]
@rafaelbn are you ok merging this although your comment was not resolved?

**Comment by rafaelbn** [comment]
Hello @tafaRU ! I wish you see you in Valencia 😄 

Devs should understand (as I explain in my team) that they should make more easy for functional to test PR. Any case, review is difficult and no much reviewers.

As easy you give the review as easy you will get reviewers

BTW, I have tried to test and runbouat is "off". Could you please rebase?

With a really simple screenshot that for dev takes 30 seconds this PR could be merged 7 months ago...

**Comment by tafaRU** [comment]
> I have tried to test and runbouat is "off". Could you please rebase?

done! You had a typo invoking ocabot :wink: 

image

@rafaelbn please try again once runboat build is ready.

**Review by rafaelbn — APPROVED** [review]
Please I encourage @driehuis to post screen shoots to get better reviewability 

Before

imagen


After

imagen


I'm not using this report at all so usually dificult to get reviewers if you don't post with videos or screenshots that I guess you have test it serveral times before PR 😄 

👍🏼

**Pull request closed without merging**
