### PR TITLE
[14.0][FIX] account_tax_balance: Fixed translation of the financial type field values

### PR DESCRIPTION
**Pull request by luiseevaquer**
**Before (14.0 stable):**

Selección_999(673)

Selección_999(676)

**After changes in this PR:**

Selección_999(674)

Selección_999(679)

### CODE REVIEW

**Review by hugho-ad — APPROVED** [review]

**Review by moylop260 — APPROVED** [review]
👍

**Review by luisg123v — APPROVED** [review]

**Comment by luiseevaquer** [comment]
Hi @pedrobaeza 

Could you review this PR, please

**Comment by pedrobaeza** [comment]
Uhm, it's weird that Odoo doesn't recognize the strings to translate. Is this something new of Odoo v14? And isn't here the risk is only having the translation of the initialization user, and not for the rest of installed languages?

**Comment by luisg123v** [comment]
Hi @pedrobaeza,

Odoo automatically makes translatable selection values when they're declared in the field itself. But, since on this case selection values are provided by calling a method, Odoo is not able to detect and make then translatable, thus needing to do it explicitly.

**Comment by luiseevaquer** [comment]
Hi @pedrobaeza 

I added in PR description screenshots with tests from OCA runbot of 14.0 stable branch and these changes

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
