### PR TITLE
[12.0][FIX] partner_statement: show only open invoices in oustanding report

### LINKED ISSUE #564: [11] Customer outstanding statement - show already reconciled invoices
Hello, 

I'm using Odoo 11 Community, on a Centos7 VPS. 
After updating to the last version of the module customer_outstanding_statement, the report shows all the invoices for the customer, not only the open ones. 

Thank you, 
Sergiu

image

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fixes https://github.com/OCA/account-financial-reporting/issues/564.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
ping: @sergiuga, @seancallahan88, @gdgellatly

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
cc @hveficent can you review this one?

**Review by HviorForgeFlow — APPROVED** [review]
Functional review 
LGTM :+1:

**Pull request closed without merging**
