### PR TITLE
[16.0] [FIX] account_financial_report: show currency name instead of dictionary

### PR DESCRIPTION
**Pull request by eLBati**
Steps:

 - Accounting > Reporting > OCA accounting reports > Journal Ledger
 - Select Date range and activate Foreign Currency

Get "{'name': 'EUR'} " in currency field

Desired: get EUR

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe the solution would be to not put in first place the whole content in the dictionary? cc @victoralmau

**Comment by victoralmau** [comment]
I understand error and fix.

Currently there are many dictionaries that could be removed in Journal Ledger: 
- account_ids_data
- partner_ids_data
- currency_ids_data
- move_ids_data
- tax_line_data
- move_line_ids_taxes_data 

and thus reduce and simplify the code. Do you think this change is necessary?

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
pre-commit is broken. Not related to this module, but it would be great if you fix it (here or in other PR).

**Comment by victoralmau** [comment]
Pre-commit is now fixed if we do a rebase.

**Comment by pedrobaeza** [comment]
OK, then we can launch the command that does the rebase on merge:

/ocabot merge patch

**Pull request merged**
