### PR TITLE
[FIX] afr_webkit_xls: incorrect debit/credit in xls trial balance

### PR DESCRIPTION
**Pull request by sbidoul**
This is a migration bug. cc/ @anthony-muschang

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by nbessi** [comment]
:+1: that said `_p` is not  the best variable name...

**Comment by sbidoul** [comment]
@nbessi agreed. I guess we'll have to live with these modules until we know more about the new v9 account reporting engine.

Can we fast-track this PR?

**Comment by anthony-muschang** [comment]
:+1:

**Pull request merged**
