### PR TITLE
[14.0][FIX] account_financial_report: Memory problems setting filters

### LINKED ISSUE #814: [account_financial_report] Memory problems setting filters to reports
Hello, we got the following error when set filters to differents reports

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6251, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6030, in _onchange_eval
    method_res = method(self)
  File "/mnt/extra-addons/account-financial-reporting/account_financial_report/wizard/general_ledger_wizard.py", line 106, in on_change_account_range
    [("code", "in", [x for x in range(start_range, end_range + 1)])]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4499, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: invalid memory alloc request size 1073741824

We have detected the following problem in the account-financial-reporting module, specifically in the code of the following files:

account-financial-reporting / account_financial_report / wizard / aged_partner_balance_wizard.py
account-financial-reporting / account_financial_report / wizard / general_ledger_wizard.py
account-financial-reporting / account_financial_report / wizard / open_items_wizard.py
account-financial-reporting / account_financial_report / wizard / trial_balance_wizard.py

The same problem appears in all of them.

The following sentence exists in code, according to the file:

self.account_ids = self.env ["account.account"]. search (
[("code", "in", [x for x in range (start_range, end_range + 1)])]
)

Or this one.

self.account_ids = self.env ["account.account"]. search (
[
("code", "in", [x for x in range (start_range, end_range + 1)]),
            ("reconcile", "=", True),
        ]
    )

If for example we have the values:

start_range = 10000000
end_range = 30000000

An attempt is made to construct a SELECT statement with an IN operator with many values, so many that the size of the statement string causes memory overflow.

SELECT ... FROM ... WHERE .... code IN (10000000, 10000001, 10000002, 10000003, 10000004, .........., 30000000)

We have tried this alternative with which we have obtained the correct result without producing memory errors.

self.account_ids = self.env ["account.account"]. search (
[("code", "> =", start_range), ("code", "<=", end_range)]
    )

Can you review it in case it is convenient to modify this module?

Thanks,
Greetings.

### PR DESCRIPTION
**Pull request by Abranes**
Here we change the implementation of `on_change_account_range` to SQL to fix memory issues.

Fixes #814

@fuentes010 @Reyes4711 @ioans73

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Instead, just use `<` and `>` with Odoo search. It should work properly.

**Comment by Abranes** [comment]
> Instead, just use `<` and `>` with Odoo search. It should work properly.

I changed it and it works fine.

**Review by fuentes73 — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Cherry-pick to v13 at 357554ce1ca141af2a92607a9e1fee940e5d95ca and to v15 at 5f49c5852dcb2e5d333d5e573b707ff38fad0d8a

**Pull request merged**
