### PR TITLE
[15.0][FIX] account_purchase_stock_report_non_billed: Fix cache miss error on currency_id computed field

### PR DESCRIPTION
**Pull request by BT-etejeda**
Fix CacheMiss error on stock.move currency_id non store computed field.

### CODE REVIEW

**Comment by BT-etejeda** [comment]
Hello @pedrobaeza @CarlosRoca13, it's a pleasure to say hi to you around here :). Could you have a look to this small change? Thanks

**Review by BT-nsanchez — APPROVED** [review]
LGTM!

**Review by BT-mgomez — APPROVED** [review]
LGTM. Thanks for taking care of coverage and lightly updating the test.

**Review by CarlosRoca13 — APPROVED** [review]
Thanks :smile: 

/ocabot merge minor

**Pull request merged**
