### PR TITLE
[14.0][MIG] account_financial_report: Migration to 14.0

### PR DESCRIPTION
**Pull request by joao-p-marques**
Supersedes https://github.com/OCA/account-financial-reporting/pull/733

Clean code and apply a **refactor** needed because of changes in Odoo for v14.

#### Refactor changes:
Since v14, Odoo defines the `__slots__` attribute in the `BaseModel` class (https://github.com/odoo/odoo/commit/ea3e39506a2b360545ec0cd1d3235e69ad16ea6c)
This makes it impossible to add attributes to an instance like it was done here in v13.
The use of the `report_data` dictionary passed between method is the closest and simplest solution to this "issue".

@Tecnativa
TT26415

@ernestotejeda @pedrobaeza @Yajo can you review please?

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by ernestotejeda — COMMENTED** [review]
Check Travis CI
Code review :+1:

**Comment by pedrobaeza** [comment]
Can you please check Travis?

**Comment by joao-p-marques** [comment]
The last push should fix Travis. Thanks!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
