### PR TITLE
[13.0][FIX] account_financial_report: Actions

### PR DESCRIPTION
**Pull request by Tardo**
cc @tecnativa TT19684

Idk what happens with commented lines in report/templates/trial_balance.xml:
- https://github.com/OCA/account-financial-reporting/blob/ef194c0bc17ad5c205698e3fd87ab87c07abe2d1/account_financial_report/report/templates/trial_balance.xml#L67
- https://github.com/OCA/account-financial-reporting/blob/ef194c0bc17ad5c205698e3fd87ab87c07abe2d1/account_financial_report/report/templates/trial_balance.xml#L566
- https://github.com/OCA/account-financial-reporting/blob/ef194c0bc17ad5c205698e3fd87ab87c07abe2d1/account_financial_report/report/templates/trial_balance.xml#L621
- https://github.com/OCA/account-financial-reporting/blob/ef194c0bc17ad5c205698e3fd87ab87c07abe2d1/account_financial_report/report/templates/trial_balance.xml#L682

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@Tardo Thank you very much for this! Was much needed.

**Review by chusamo — APPROVED** [review]
Tested all reports views in Runbot and LGTM. Thank you

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I'm missing the export button, and the margin for the results shown.

In v12:

Selección_001

In v13:

Selección_002

Other thing that I don't know if it's part of this PR is that generated PDF contains a lot of margins both up and down the page.

**Comment by Tardo** [comment]
changes done

**Review by pedrobaeza — APPROVED** [review]
Working as expected. Please fw-port it to v14

**Comment by pedrobaeza** [comment]
Let's merge it for have it fixed:

/ocabot merge minor

**Pull request merged**
