### PR TITLE
[16.0] Forward port 4 fixes from v14 to v16

### PR DESCRIPTION
**Pull request by alexis-via**
This is a pure-bugfix PR which forward-port 3 fixes:

- 2 fixes from https://github.com/OCA/account-financial-reporting/pull/914
- 1 fix from https://github.com/OCA/account-financial-reporting/pull/1238

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please do the same fw-port to 15 and 17.

**Comment by pedrobaeza** [comment]
Sorry, I have now seen all of them. Thanks for the effort :)

**Review by pedrobaeza — APPROVED** [review]

**Comment by alexis-via** [comment]
I forward-ported 1 more stupid sorting bug https://github.com/OCA/account-financial-reporting/pull/1242
I also forward-ported the change I had to make in v15 to make the forward-port work, which is a good change anyway.

**Review by florian-dacosta — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Not sure if latest change affects Italian localization cc @eLBati

**Pull request merged**
