### PR TITLE
[10.0] account_tax_balance performance

### PR DESCRIPTION
**Pull request by sbidoul**
forward port of #293

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by eLBati — APPROVED** [review]
Thanks

**Comment by pedrobaeza** [comment]
Can I squash the commits?

**Comment by sbidoul** [comment]
@pedrobaeza better keep the commits as they are the same as in the 9.0 branch.

**Comment by pedrobaeza** [comment]
OK, you know that one commit for only bumping the version is not my favorite, but I respect your decision. Merging...

**Pull request merged**
