### PR TITLE
8.0 add modules intrastat_base and intrastat_product

### PR DESCRIPTION
**Pull request by alexis-via**
The module were moved from lp:new-report-intrastat

### CODE REVIEW

**Comment by eLBati** [comment]
Hello @alexis-via , it seems something went wrong with this PR: there are so many commits and so many files changed

**Comment by alexis-via** [comment]
@eLBati yes, it seems something went wrong... but I don't know what went wrong exactly. I used the same "process" to migrate l10n_fr_intrastat_product and l10n_fr_intrastat_service and it worked well. Note that I am not an expert of the LP to github migration.

**Comment by alexis-via** [comment]
OK, let's try a new migration in another branch and see if I get better results.

**Comment by jbaudoux** [comment]
Hi,
I signed and sent CLA last year. Membership for 2014 and 2015 (recently) 
has been paid.
This should be solved once I'll be part of OCA database.
Kind Regards,
J-E (jbaudoux)

**Pull request closed without merging**
