### PR TITLE
[FIX] set apropriate link to style file

### PR DESCRIPTION
**Pull request by i-vyshnevska**
related to https://github.com/OCA/account-financial-reporting/issues/571

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Sorry, but as stated on the commit, this is putting a non desired background and now the renaming is reverted, so there's no sense for this.

**Comment by i-vyshnevska** [comment]
@pedrobaeza if you want to have specific color so set it in styles in https://github.com/OCA/account-financial-reporting/blob/2fe67661b1433b810902727fa1db8ff8c3ea210a/account_financial_report/static/src/css/report.css#L98 but this is totally wrong to keep broken files, it'll give you unpredictable behavior

**Comment by pedrobaeza** [comment]
Offending variables removed in https://github.com/OCA/account-financial-reporting/commit/44c30b45517843be0c4a710469c5b6afae1036ab

**Comment by i-vyshnevska** [comment]
for v 10 pls too

**Comment by pedrobaeza** [comment]
Done in d52934409bf396de6b12fa2e819190598150181f

**Pull request closed without merging**
