### PR TITLE
[16.0][mig] mis_builder_cash_flow

### PR DESCRIPTION
**Pull request by aktiv-heli-kantawala**

### CODE REVIEW

**Comment by andreampiovesana** [comment]
why use account_internal_type and not account_type in the related field?
    account_internal_type = fields.Selection(
        related="account_id.account_type", readonly=True
    )

**Review by andreampiovesana — CHANGES_REQUESTED** [review]
why use account_internal_type and not account_type in the related field?
account_internal_type = fields.Selection(
related="account_id.account_type", readonly=True
)
and change also in mis_builder_cash_flow/data/mis_report.xml from account_internal_type to account_type

**Review by andreampiovesana — CHANGES_REQUESTED** [review]
in data/mis_report.xml 
('account_internal_type', '=', 'liquidity') ->  ('account_type', '=', 'asset_cash')
('account_internal_type', '=', 'receivable') ->  ('account_type', '=', 'asset_receivable')
('account_internal_type', '=', 'payable') ->  ('account_type', '=', 'liability_payable')

**Comment by pedrobaeza** [comment]
Superseded by #1049

**Pull request closed without merging**
