### PR TITLE
[12.0][IMP] account_financial_report: change report access groups to only 'Show Full Accounting Features'

### PR DESCRIPTION
**Pull request by ramiadavid**
Backport of #939 

@pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by ramiadavid** [comment]
Hi @pedrobaeza What is it codecov/project and why it fails in many PR's is it not important?

**Comment by pedrobaeza** [comment]
It's a measure of the test coverage, but I'm not sure is working correctly on all of the cases. It's ignored most of the times as it's not critical for the module to work, but just a quality measure.

In this PR the problem may be the Travis failing, that don't pass to Codecov all the data.

Anyway, the backport to this older versions is not convenient unless you have explicit interest on it. To cover the currently supported versions is enough as a good contributor :)

**Comment by ramiadavid** [comment]
@pedrobaeza Ok, so I cancel the PR for the previous versions? v11 v10 v9

**Comment by pedrobaeza** [comment]
What you prefer. As you have done them already, maybe someone wants it, so let's see the community reaction.

**Pull request closed without merging**
