### PR TITLE
[13.0][FIX] account_financial_report: filter cancelled journal items

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
Fixes for not showing Journal Items of canceled Journal Entries when looking for Posted and Unposted moves.
Also a little fix for showing partner name in Journal Ledger. (associated with migration to v12 to v13)

cc @ForgeFlow @LoisRForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, LGTM

**Comment by pedrobaeza** [comment]
Isn't possible all these domains can be in the abstract part for not duplicating that code?

**Comment by JoanSForgeFlow** [comment]
I agree, I will try to increase the abstract part for not duplicating code and increase the readability of the code as soon as possible.

**Comment by JoanSForgeFlow** [comment]
@pedrobaeza I have improved the code a little bit. Sorry for the delay.

**Review by pedrobaeza — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
I'm afraid this broke the journal ledger wizard as it does not inherit from the abstract wizard.

```
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 380, in call_kw
    method = getattr(type(model), name)
AttributeError: type object 'journal.ledger.report.wizard' has no attribute 'button_export_xlsx'
```

**Pull request merged**
