### PR TITLE
9.0 forward port

### PR DESCRIPTION
**Pull request by sbidoul**
This is a simple `git merge 8.0` into 9.0.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
How this deals with https://github.com/OCA/account-financial-reporting/pull/147?

**Comment by sbidoul** [comment]
@pedrobaeza We'll rebase #147.

**Comment by pedrobaeza** [comment]
Isn't better to cherry-pick these commits in #147?

**Comment by sbidoul** [comment]
It's much easier like this. And it gives a clear view in the history that 9.0 has all the last improvements from 8.0.

**Comment by pedrobaeza** [comment]
OK, fast-tracking then as it straight-forward

**Comment by sbidoul** [comment]
Thanks, Pedro!

**Pull request merged**
