### PR TITLE
mis_builder: fix typo, causes crash if report_xslx is missing

### PR DESCRIPTION
**Pull request by lepistone**
ping @sbidoul @lmignon @adrienpeiffer 

Thanks!

### CODE REVIEW

**Comment by lepistone** [comment]
WIP: still crashes for another reason.

**Comment by lepistone** [comment]
It now probably works, but it is a bit hacky.

I am letting @sbidoul and the others authors of the module choose what you prefer. Thanks!

EDIT: removed a section "other options" that didn't make sense.

**Comment by sbidoul** [comment]
We depend on report_xlsx already, it's just that the module is imported because of the `static` directory.

I'm fine with your approach. 

:+1:

**Comment by lepistone** [comment]
Ah yes @sbidoul, I was making a mess because I didn't have `reporting-engine` available, but still we need to handle `static`. So I agree with you, and my patch is OK like this. Thanks!

**Comment by sbidoul** [comment]
Ok. I think I can fast track this.

**Pull request merged**
