### PR TITLE
[UPD] POT files

### PR DESCRIPTION
**Pull request by StefanRijnhart**
[UPD] POT files
ADD] Dutch translations

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's an error on one file. Please check it.

**Comment by StefanRijnhart** [comment]
Thanks @pedrobaeza! My older version of Odoo 7.0 server did not signal the corruption that it created itself in the export of a POT-file.

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by max3903** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
