### PR TITLE
[REF] account_tax_balance: Allow to override query

### PR DESCRIPTION
**Pull request by SirAionTech**
After this PR, other modules can edit the query or its parameters before execution.

In our use case this is useful because we want to gather the moves by another field instead of `date`.

### CODE REVIEW

**Review by rvalyi — CHANGES_REQUESTED** [review]
the docstring doesn't match anymore with what the extracted method does.

**Comment by SirAionTech** [comment]
> the docstring doesn't match anymore with what the extracted method does.

Thanks for having a look!
I moved the docstring in the extracted method because I thought it was describing the query structure, but indeed the extracted method does not return any ID.
I restored the docstring where it was before, let me know if it looks better now

**Review by rvalyi — APPROVED** [review]
yes I think it's better because it properly describes was is returned by the method.

**Review by sergiocorato — APPROVED** [review]

**Pull request merged**
