### PR TITLE
[11.0][MIG] account_financial_report_date_range

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Are you still using these ugly reports?

**Comment by MiquelRForgeFlow** [comment]
ping: @lreficent

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza haha not really, but it is auto-install with account and date_range in v10 so odoo logs the warning of module missing in v11... But thinking it twice, you are right: You can close it and I will just uninstall after migration or We can just fast-forward it for completeness (as it is already migrated). Whatever you prefer :wink:

**Comment by pedrobaeza** [comment]
Yeah, as Odoo has removed all reports in v12, it's not interesting to preserve this IMO.

**Comment by MiquelRForgeFlow** [comment]
This is v11. I mean, I like completeness!

**Comment by pedrobaeza** [comment]
It's not a question of completeness, but as said, that reports are not used, so you don't need that extra feature. If you have it in v10, it will probably not being used already, so you can uninstall there, but if so, just teach your users to not use it anymore and uninstall on v11.

**Comment by MiquelRForgeFlow** [comment]
Who knows, maybe really exist somebody who use it. But I made a work and I don't like to see my work wasted. Efforts should be compensated.

**Review by LoisRForgeFlow — APPROVED** [review]
My 2 cents.

**Review by pedrobaeza — APPROVED** [review]
OK, let's use it...

**Pull request merged**
