### PR TITLE
[12.0][ADD] mis_builder_cash_flow module

### PR DESCRIPTION
**Pull request by jjscarafia**
Supersedes https://github.com/OCA/mis-builder/pull/154

### CODE REVIEW

**Comment by rvalyi** [comment]
cc @mileo

**Comment by jjscarafia** [comment]
@fclementic2c @etobella @jbeficent @pedrobaeza @sbidoul 
I've moved https://github.com/OCA/mis-builder/pull/154 to this repository with small changes.
Thanks

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Comment by etobella** [comment]
@jjscarafia I added some tests on #623 Maybe you could add them here :wink:

**Review by jarroyomorales — APPROVED** [review]
Nice! :+1:

**Comment by jjscarafia** [comment]
great @etobella . Done! thanks!

**Review by rvalyi — APPROVED** [review]

**Comment by jjscarafia** [comment]
any news on this? anything else needed?

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
