### PR TITLE
[IMP] Fix vat_report, fix ND/NC

### PR DESCRIPTION
**Pull request by samsagaz**
Code to fix issue reported #806

### CODE REVIEW

**Comment by wpichler** [comment]
Our customer was also hit by this bug - i can confirm that this fix does work as expected.

**Comment by samsagaz** [comment]
> Our customer was also hit by this bug - i can confirm that this fix does work as expected.

good news that it worked for you too!

**Comment by wpichler** [comment]
Yep - thanks for your work @samsagaz

Can you request a review from a maintainer to get this fix into main repo ?

**Comment by samsagaz** [comment]
> Yep - thanks for your work @samsagaz
> 
> Can you request a review from a maintainer to get this fix into main repo ?

I don't know how to make that request :/

I just opened the PR.

**Pull request closed without merging**
