### PR TITLE
wip - [7.0][IMP] account_financial_report_webkit general_ledger reduce sql …

### PR DESCRIPTION
**Pull request by tfossoulw**
…query nbr

This redure drastically the number of sql query to the database so optimise the report generation.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is changing some methods signature, it's a very old version and Travis is red, so I don't think this is going to be merged easily, as for sure no reviewers will arise. I think you should better focus on migrate your customers to newer versions.

Any way, I let it opened to see a bit.

@hbrunn what do you think about this?

**Comment by hbrunn** [comment]
I don't think we should demotivate people working on old versions. But as you I'd be very cautious to merge this, because we don't have proper tests for 7.0. And I myself won't review it because I'm done with 7.0 indeed.

**Comment by pedrobaeza** [comment]
It's not to demotivate, but being realistic. This is changing API signatures, and other modules depending on this one (OCA or not), might break after this change. The risk can be taken over a version well maintained (v10, v11, even v8...), but not v7

**Comment by tfossoulw** [comment]
I could also keep the method signature intact but adapt the method to allow 1 or more "account_id".
Then other modules depending on this one shouldn't be impacted by this commit. ?

**Comment by pedrobaeza** [comment]
There is the same problem, as if you pass several accounts, other modules won't process this multi-record properly.

**Comment by tfossoulw** [comment]
No, you allow to pass either one or several account. So other modules could continue to work with it.

**Comment by agb80** [comment]
As v8 and v7 versions for impacted module are pretty similar another approach could be create the PR for v8 that have many more test and when accepted for v8 make a backport for v7.

My 2cents

**Pull request closed without merging**
