### PR TITLE
[14.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by etobella**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by patrickt-oforce** [comment]
@pedrobaeza can this be rebased to include uodated configuration of pre-commit?

**Comment by pedrobaeza** [comment]
This one is the update pre-commit configuration. The problem is that there are failing according new checks, so a manual intervention should be done fixing such failings. You can take this PR as base, and fix those failing in another PR.

**Comment by patrickt-oforce** [comment]
Hi @pedrobaeza thank you for your reply, i've opened PR #1086 that fix some issue of pre-commit, but i don't know how to manage suggestion about replace position in failing pre-commit on that PR

**Comment by pedrobaeza** [comment]
Superseded by #1086

**Comment by pedrobaeza** [comment]
Hey, I see that the PR doesn't include the updated template.

**Comment by patrickt-oforce** [comment]
> Hey, I see that the PR doesn't include the updated template.

I've based my branch on this PR

**Review by pedrobaeza — APPROVED** [review]
Well, this seems to be correct now:

/ocabot merge patch

**Review by patrickt-oforce — APPROVED** [review]

**Pull request merged**
