### PR TITLE
[15.0][FIX] account_tax_balance: disable readme pylint in migrations folder

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Disable missing-readme pylint check so other modules' pre-commit doesn't fail.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think you have an old version of pylint in your local, and that's why you get that problem, but the CI was green before this.

**Comment by mariadforgeflow** [comment]
Hi @pedrobaeza! I've just rebased in my local and I still get the missing-readme error in pre-commit. Is there any other thing I can do? Thank you for your time:)

**Comment by pedrobaeza** [comment]
But the CI was previously red here on GitHub before this?

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza @AaronHForgeFlow ready to merge

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
