### PR TITLE
[12.0][FIX] account_financial_report: Update to bootstrap 4

### PR DESCRIPTION
**Pull request by pedroslopez**
Fixes footer on PDF reports to render properly with bootstrap 4 changes

### CODE REVIEW

**Comment by danimaribeiro** [comment]
Tested :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please put screenshots of before and after

**Comment by pedroslopez** [comment]
@pedrobaeza Screenshots, as requested:

**Before:** 

Screen Shot 2019-07-25 at 12 01 42 AM


**After:**

Screen Shot 2019-07-25 at 12 03 45 AM

**Review by pedrobaeza — APPROVED** [review]

**Pull request closed without merging**
