### PR TITLE
[7.0] account_export_csv: fix journals filter for trial balance

### PR DESCRIPTION
**Pull request by ludogre**
Here is a fix to consider journals that are filtered in the export wizard for trial balance.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thank you for the fix, @ludogre! I have reviewed your code and I would love to approve it so that it can be merged. However, our gitbot suspects that you have not submitted a CLA that allows the OCA to adopt your suggested change. Or maybe your github handle was not entered correctly in our system. Can you have a look?

**Comment by ludogre** [comment]
OK. I've just signed the ICLA.

**Comment by ludogre** [comment]
I have signed the ICLA.  Can someone remove the "Pending CLA" label and accept my pull request?

**Review by StefanRijnhart — APPROVED** [review]
ICLA confirmed manually as CLAbot let us down a bit.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Thanks for the fix

**Comment by StefanRijnhart** [comment]
I think our travis config is suffering from bitrot in this old branch. Merging regardless.

**Pull request merged**
