### PR TITLE
 Add static description to get a proper look on app store

### PR DESCRIPTION
**Pull request by lmignon**
The description has been generated using rst2html5.
The path to the images has been manually fixed by removing 'static/description/' from the path.
The body element has been replaced by a section wrapping the whole content.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by lmignon** [comment]
@pedrobaeza @laetitia-gangloff  Thank you for your review. I've also fixed the module title according to https://github.com/OCA/maintainer-tools/commit/d51c38f6b269d2d633d041109d04ee60992dafd8

**Comment by pedrobaeza** [comment]
Thanks!

**Comment by adrienpeiffer** [comment]
:+1:

**Pull request merged**
