### PR TITLE
[12.0][ADD] partner_statement: migration scripts to v12

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Adds migration scripts.

### CODE REVIEW

**Comment by gdgellatly** [comment]
@mreficent given it is a different module, and you could just drop the tables if they exist is it really necessary? Anyway I have no objections to the actual code if you think it is, so consider this a +1.

**Comment by MiquelRForgeFlow** [comment]
We have migrated several data bases with this, it works fine.

**Review by gdgellatly — APPROVED** [review]

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
