### PR TITLE
[10.0][MIG]account_move_line_export_xls

### PR DESCRIPTION
**Pull request by luc-demeyer**
this port depends on report_xlsx_helper which is the functional equivalent of the 8.0 report_xls module.
Cf. https://github.com/OCA/reporting-engine/pull/204.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please, could you squash commits?

Also, could you explain a bit why you need `report_xlsx_helper` instead of `report_xlsx`?

**Comment by ovnicraft** [comment]
@luc-demeyer helper was merged on reporting-engine.
@mreficent `_render()` its a function from helper module to render in easy way a field from object, its used here https://github.com/OCA/account-financial-reporting/pull/449/files#diff-aecd311ccc645bab9ba1a5e95c16a939R42

**Comment by luc-demeyer** [comment]
all green, I think this one is ready for merge/.

**Comment by ovnicraft** [comment]
LGTM

**Comment by MiquelRForgeFlow** [comment]
Please, could you squash commits?

**Comment by luc-demeyer** [comment]
@mreficent : squash done

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
