### PR TITLE
8.0 account financial report horizontal

### PR DESCRIPTION
**Pull request by hbrunn**
This is basically a rewrite to get rid of the inherited 6.0 code. So better ignore the diff and have a look at the code.

I inject a context key to determine which reports to show, so the most probable place where I might have messed up is in https://github.com/hbrunn/account-financial-reporting/blob/8.0-account_financial_report_horizontal/account_financial_report_horizontal/models/account_financial_report.py#L28 and `_get_children_by_order`

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@gurneyalex, can you please activate runbot here to try this module?

**Comment by StefanRijnhart** [comment]
Nice! Failing tests are unrelated. The same errors occur in other PRs.

You can remove views/account_report.xml.

In README.rst, please change the description to reflect that this is no longer a 'rewrite of the financial reports from OpenERP 6.0' but instead only a cosmetic change to the existing reports.

Last remark: conventionally, in our region, the sign is reversed in the right column so that it does not usually contain negative amounts. However, this should probably not be changed to preserve consistency with the 'show debit/credit' option, which makes it clear that the amounts are actually the balances of the accounts, with its proper sign.

**Comment by hbrunn** [comment]
@StefanRijnhart thanks!

Here the updated README.rst for convenience: https://github.com/hbrunn/account-financial-reporting/blob/8.0-account_financial_report_horizontal/account_financial_report_horizontal/README.rst

If anybody knows other countries where this reports are customary, please let me know

**Comment by StefanRijnhart** [comment]
Thanks for the changes, :+1: (code review, test)

**Comment by sbidoul** [comment]
Red because of #67

**Comment by pedrobaeza** [comment]
Please rebase to get green results

**Comment by hbrunn** [comment]
@pedrobaeza done

**Comment by pedrobaeza** [comment]
:+1: Tried on runbot

**Pull request merged**
