### PR TITLE
OCA reports XLSX: Better override to define workbook creation options

### PR DESCRIPTION
**Pull request by jcoux**
Little modification to fix this issue:
https://github.com/OCA/account-financial-reporting/issues/241

Depends of PR:
https://github.com/OCA/reporting-engine/pull/77

This PR contains a revert of https://github.com/OCA/account-financial-reporting/pull/229 which is useless now.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
After the other merge

**Comment by damdam-s** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@damdam-s, you should use new approval system in order to get proper statistics in the future

**Review by damdam-s — APPROVED** [review]

**Comment by damdam-s** [comment]
@pedrobaeza thanks, i didn't notice this feature yet !

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
