### PR TITLE
[13.0][FIX] account_financial_report: Fix regressions in open items report due to Odoo Structural changes

### PR DESCRIPTION
**Pull request by nbessi**
- Correct columns name in XLSX report
- Use correct field for label

### CODE REVIEW

**Review by Tonow-c2c — APPROVED** [review]
LGTM

**Comment by JordiBForgeFlow** [comment]
cc @JoanSForgeFlow can you check? We have some pending forward ports to do from our branch in v12

**Comment by JoanSForgeFlow** [comment]
@JordiBForgeFlow Yes, we have forward ported the changes in v12, these two fixes are included.

@nbessi Would you mind reviewing it here #682 please? Thanks a lot

**Comment by pedrobaeza** [comment]
Closing as this has been fixed in other PR.

**Pull request closed without merging**
