### PR TITLE
[14.0][FIX] account_financial_report: Run compute in multi

### PR DESCRIPTION
**Pull request by hildickethan**
- Run computes in batch
- Added recursive to the compute

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's a new attribute `recursive=True` in the ORM that would benefit these fields computation. Can you please check?

**Comment by hildickethan** [comment]
> There's a new attribute `recursive=True` in the ORM that would benefit these fields computation. Can you please check?

Added it, it seemed to work fine. I presume it's to compute the parents `complete_name` too?

**Review by pedrobaeza — APPROVED** [review]
`recursive` helps to process the compute in the best order for performance and completeness.

**Comment by hildickethan** [comment]
> `recursive` helps to process the compute in the best order for performance and completeness.

Nice, is there any documentation for this new attribute? I didn't see it in either the 14.0 or 15.0 docs

**Comment by pedrobaeza** [comment]
I'm afraid not.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
