### PR TITLE
[IMP] mis_builder: _get_additional_query_filter on period model

### PR DESCRIPTION
**Pull request by sbidoul**
This is a better api that is more consistent in case we want to have an analytic filter on the columns.

Thanks @jbeficent for the productive discussion and tests of this new API.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by JordiBForgeFlow** [comment]
:+1: Thanks to for your insights @sbidoul 

This would be the result of use with separate module "mis_builder_analytic_account". I'll propose a separate PR for that:
image

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by alexis-via** [comment]
:+1:

**Pull request merged**
