### PR TITLE
[16.0][IMP] account_financial_report: VAT report fields translation

### PR DESCRIPTION
**Pull request by toita86**
fwp of: https://github.com/OCA/account-financial-reporting/pull/1154

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by norlinhenrik — APPROVED** [review]
Functional test
Date format changed from static "2024-12-31" to language specific (US: "12/31/2024").

**Comment by francesco-ooops** [comment]
@etobella can this be merged? thanks!

**Comment by francesco-ooops** [comment]
@toita86 can you rebase?

**Review by etobella — APPROVED** [review]
Makes sense to me

/ocabot merge minor

**Comment by etobella** [comment]
@toita86 Can you rebase manually? :pray:

**Comment by toita86** [comment]
@etobella No problem, done!

**Pull request merged**
