### PR TITLE
[17.0][IMP] account_financial_report: add custom intervals for aged partner report

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
Fw port to v17 #1083

@Tecnativa
TT45574

@pilarvargas-tecnativa @pedrobaeza

### CODE REVIEW

**Comment by pilarvargas-tecnativa** [comment]
Can you remove the "or" between the buttons?

https://github.com/OCA/account-financial-reporting/blob/765fd8cf7ce20b74218442094c7fdb243498cd52/account_financial_report/wizard/aged_partner_balance_wizard_view.xml#L65-L87

**Comment by carolinafernandez-tecnativa** [comment]
> Can you remove the "or" between the buttons?
> 
> https://github.com/OCA/account-financial-reporting/blob/765fd8cf7ce20b74218442094c7fdb243498cd52/account_financial_report/wizard/aged_partner_balance_wizard_view.xml#L65-L87

Done! thanks :)

**Comment by pedrobaeza** [comment]
Pending on the changes to apply in #1140 cc @carolinafernandez-tecnativa

**Comment by carolinafernandez-tecnativa** [comment]
> Pending on the changes to apply in #1140 cc @carolinafernandez-tecnativa

Changes added

**Review by pilarvargas-tecnativa — APPROVED** [review]
thanks! :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
