### PR TITLE
[FIX] account_financial_report: get module compatible with HomeMenu widget added by web_enterprise module

### PR DESCRIPTION
**Pull request by tafaRU**
Steps to reproduce:

* install account_financial_report module alongside Odoo Enterprise
* open General Ledger report
* click on View button
* click on Home button or by using the shortcut (Shift +h)

Current behaviour:

```
Uncaught TypeError: currentController.widget.on_detach_callback is not a function

http://localhost:8069/web/static/src/js/chrome/action_manager.js:94
Traceback:
TypeError: currentController.widget.on_detach_callback is not a function
    at Class.on_detach_callback (http://localhost:8069/web/static/src/js/chrome/action_manager.js:94:38)
    at http://localhost:8069/web/static/src/js/core/dom.js:175:26
    at Function._.each._.forEach (http://localhost:8069/web/static/lib/underscore/underscore.js:145:9)
    at Object.detach (http://localhost:8069/web/static/src/js/core/dom.js:173:11)
    at http://localhost:8069/web_enterprise/static/src/js/web_client.js:289:21
    at http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3275:77)
    at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)

```
In addition, after having implemented on_detach_callback, if I click on the icon chevron left or by using the shortcut (Alt+Shift+h), I get the following error:

```
Uncaught TypeError: currentController.widget.on_attach_callback is not a function
http://localhost:8069/web/static/src/js/chrome/action_manager.js:84
Traceback:
TypeError: currentController.widget.on_attach_callback is not a function
    at Class.on_attach_callback (http://localhost:8069/web/static/src/js/chrome/action_manager.js:84:38)
    at http://localhost:8069/web/static/src/js/core/dom.js:38:22
    at Function._.each._.forEach (http://localhost:8069/web/static/lib/underscore/underscore.js:145:9)
    at _notify (http://localhost:8069/web/static/src/js/core/dom.js:36:7)
    at Object.append (http://localhost:8069/web/static/src/js/core/dom.js:60:13)
    at Class.toggle_home_menu (http://localhost:8069/web_enterprise/static/src/js/web_client.js:305:17)
    at Class.self.toggle_home_menu (http://localhost:8069/web_enterprise/static/src/js/widgets/debug_manager.js:21:38)
    at Class._onHideHomeMenu (http://localhost:8069/web_enterprise/static/src/js/web_client.js:329:18)
    at Class.<anonymous> (http://localhost:8069/web/static/src/js/core/mixins.js:278:23)
    at Class.trigger (http://localhost:8069/web/static/src/js/core/mixins.js:225:31)
```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this compatible with community?

**Comment by tafaRU** [comment]
> Is this compatible with community?

@pedrobaeza, it would seem do not cause side effects, but more tests are surely needed.

**Review by SimoRubi — APPROVED** [review]
Thanks!
Tried locally in both CE and EE, looks good.
Also reviewed the code: it fixes the issue and I see no side effects so it's 👍🏼 for me.

These methods are not actually required for a widget (https://github.com/odoo/odoo/blob/1440c8be0337c89e3d67d6d93e614c269c8689f1/addons/web/static/src/js/core/widget.js#L24) so the action manager should not assume (here https://github.com/odoo/odoo/blob/867de2bad3f6096098cb47611bcf0096b85e24b8/addons/web/static/src/js/chrome/action_manager.js#L84) such methods to be there.

Could you open an issue (or a PR if you already have an idea of the implementation) in the upstream in order to report this behavior?

**Comment by tafaRU** [comment]
@SimoRubi 
> These methods are not actually required for a widget (https://github.com/odoo/odoo/blob/1440c8be0337c89e3d67d6d93e614c269c8689f1/addons/web/static/src/js/core/widget.js#L2

Is your statement only based on the class documentation that you have linked?

**Comment by SimoRubi** [comment]
Yes that should point out how to create a widget, and looks like that widget would crash with the same error you fixed in this PR when handled by the action manager in https://github.com/odoo/odoo/blob/867de2bad3f6096098cb47611bcf0096b85e24b8/addons/web/static/src/js/chrome/action_manager.js#L84

**Pull request merged**
