### PR TITLE
[10.0] mis_builder: fix indent style and other small improvements

### LINKED ISSUE #271: [10.0] mis_builder: KPI style identation only applied in Excel export

### PR DESCRIPTION
**Pull request by sbidoul**
- fixes #271 
- improve robustness in presence of missing expressions
- add some missing `depends` in compute methods
- make some methods protected (these should never have been public in the first place)
- better form for report column declaration

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@sbidoul I am not sure how to test this. Can you send me a screenshot?

**Comment by sbidoul** [comment]
Hi @jbeficent here is a couple of screenshots with indenting styles.

HTML

image

Excel

image

**Comment by alexis-via** [comment]
Thanks for these improvements :+1:

**Review by elicoidal — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
@pedrobaeza can you please avoid squashing my commits when merging: I strive to create a meaningful commit history with proper messages and one commit per feature/fix.

**Comment by pedrobaeza** [comment]
I have squashed them because it's no meaningful outside the PR: some of the commits are for amending things on the main purpose.

**Comment by sbidoul** [comment]
That's not correct. All commits in this PR where autonomous. Now we have one big messy commit on the 10.0 branch.

**Comment by pedrobaeza** [comment]
Seeing commits like "[FIX] mis_builder: missing depends in compute method" or "[IMP] mis_builder: protected methods" or "[IMP] mis_builder: subkpi.kpi_id is a required field" that are patches, I thought they were disposable (at least you can't deny that these 3 out of 6 are). Please next time tell me to avoid this confusion and squash as we have always said by logical set.

**Comment by adrienpeiffer** [comment]
I fully agree with @sbidoul. In addition to this, all commits of Stéphane are signed with a GPG key. And now the signature is lost in the big commit.

**Comment by pedrobaeza** [comment]
I repeat that 3 out of 6 commits are totally disposable. Next time, please specify explicitly to not squash commits, and I'll ask for this cleanup and merge as is.

**Comment by adrienpeiffer** [comment]
> please specify explicitly to not squash commits

I think that the default value for this purpose it's to not sqash commit. And for me you have to ask to the author of the PR to squash commit himself.

**Comment by pedrobaeza** [comment]
You (Acsone) are the only one that have problems with this till now.

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza The author should be the one who decide to squash or not. Keeping history is sometimes important. You never use git blame ?

**Comment by adrienpeiffer** [comment]
@pedrobaeza I find your last comment totally inappropriate. It's my point of view. Please do not include the entire company. For my part, I close the debate. I hope this can be discussed in the PSC.

**Comment by pedrobaeza** [comment]
OK, I'm only saying what I'm observing right now. I don't want to upset anyone.

**Pull request merged**
