### PR TITLE
[16.0][FIX] account_financial_report: optimize computation of analytic accounts

### PR DESCRIPTION
**Pull request by yajo**
Installing the module in a big DB was very slow.

I applied several optimizations to the method for working better with big datasets:
- Prefetch all analytic account distribution.
- Batch writes as much as possible.

@moduon MT-4982

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please @norlinhenrik @gurneyalex @rousseldenis could take a look here? We cannot install in a BIG 16 DB. Thanks! 😄 ❤️

**Review by rafaelbn — APPROVED** [review]
Tested in production 👍🏼 

👍🏼 Now I can install
👎🏼 Before never install

**Review by EmilioPascual — APPROVED** [review]

**Review by edlopen — APPROVED** [review]
LGTM

**Comment by norlinhenrik** [comment]
Nice performance improvement!

In my code review, I first thought that `account` referred to regular account. I would prefer using the terms `batch_by_analytic_account` and `analytic_account_id` to be clear.

**Comment by pedrobaeza** [comment]
Check also #1081

**Comment by yajo** [comment]
@norlinhenrik applied.

@pedrobaeza I saw that, but it's a draft and involves behavioral changes. This one is just a performance optimization that can improve the current implementation, independently of what's decided there finally.

**Review by pedrobaeza — APPROVED** [review]
OK, let's go with it!

/ocabot merge patch

**Pull request merged**
