### PR TITLE
[10.0] Foreign currency total in xlsx General ledger report

### PR DESCRIPTION
**Pull request by SimoRubi**
Adding foreign currency total in xlsx General ledger report; 
adding foreign currency totals in open items report;
adding total_due total in open items report

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@SimoRubi Please make sure that you coordinate with @hveficent, as he is doing the same changes in 11.0 https://github.com/OCA/account-financial-reporting/pull/403

**Comment by SimoRubi** [comment]
Hi @jbeficent, I see @hveficent is doing a much more massive modification to reports, I'd just like to bring the changes that we did for General Ledger (in https://github.com/OCA/account-financial-reporting/pull/390) to the Open Items report.

For instance, I'd leave the `foreign_currency` flag as a v11 feature if you agree.

**Comment by HviorForgeFlow** [comment]
I will be attending this PR in order to get ideas and review. I would rather not to have so many changes made, I think I've done too many steps further and code has lost some consistence, but reports now seems to be displayed precisely, alike as reviewers demand. IMO will be important to do some refactor after adding foreign currency to all reports.

**Review by stevech091 — APPROVED** [review]
functional reviewer ok

**Comment by SimoRubi** [comment]
@hveficent I have completed the changes here, could you please review?

**Comment by HviorForgeFlow** [comment]
@SimoRubi 
General Ledger:
Initial and Final Partner Balances are not displayed in pdf view.
image

That happens when xml template look for "account_or_partner_object.currency_name", so it can't find any field related to report_aged_partner_balance_partner.currency_name. That field must be referenced in case of partner to report_aged_partner_balance_partner.report_account_id.currency_id.

Open Items:
Foreign currency balances that don't have an account with second currency should not show any number. Instead of 0.0 should show blank field.
image

Pdf and xlsx views display by default two decimals instead of show decimals depending on res_currency.decimal_placement variable.

That review has nothing to do with code you've added. It is just awesome. I took several references in #403.

I'd appreciate if you can review my work in order to build them simultaneous in both versions without major changes between.

Thanks for your contribution :smiley:

**Comment by SimoRubi** [comment]
@hveficent in General Ledger, sums are not displayed on partners because, as far as I know, there is no concept like a 'currency associated to a partner' because a partner might have several journal entries in different currencies and the total would make no sense.
On the other hand there is a 'currency associated to an account', that's why we have totals there.

I've backported part of the decimals management you used in https://github.com/OCA/account-financial-reporting/pull/403, but I can't manage to hide the 0.0 and I can't find how you did it in code, do you have any advice?

**Comment by HviorForgeFlow** [comment]
Yes 'currency associated to a partner' is so weird, but according that account you can associate with account's currency type. I think that case will solve 0.0 issues, but I'm not sure. Red travis btw

**Comment by SimoRubi** [comment]
@hveficent travis fixed, sorry but I don't get what you said about 0.0 issue and partners/accounts association

**Comment by JordiBForgeFlow** [comment]
@SimoRubi In my opinion either this PR is a backport of #403, or we merge what is here and we forward port these changes in v10 to #403. But the variation between v10 and v11 should be limited to the table renames and the addition of dynamic views. All the other logic should be the same. Otherwise this is going to be impossible to maintain.

@hveficent tells me that your model of queries is different.

I am going to try to backport #403 to a separate PR in v10.

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Adding this line at https://github.com/SimoRubi/account-financial-reporting/blob/9261493e0bd433868fac3c298edc6e3101f49055/account_financial_report_qweb/report/open_items_xlsx.py#L119
my_object.currency_id = my_object.report_account_id.currency_id

**Comment by SimoRubi** [comment]
@hveficent thanks again for your PR, just needed a few fixes for Travis, is it ok now for you and @jbeficent ?

**Comment by SimoRubi** [comment]
Closing as superseded by https://github.com/OCA/account-financial-reporting/pull/424

**Pull request closed without merging**
