### PR TITLE
[11.0][account_financial_report] fix broken wizard views in afr. 

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Forward port of PR #460 

cc @alexis-via

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]

**Comment by alexis-via** [comment]
An alternative to the removal of many2many_tags would be to invite people to install the OCA web module web_widget_many2many_tags_multi_selection (cf https://github.com/OCA/web/tree/11.0/web_widget_many2many_tags_multi_selection). I was not aware of this module... Pedro showed it to me right now.

**Comment by ovnicraft** [comment]
@alexis-via introduce this new dependence could be in a new PR, by now i tested and works fine this.

**Review by rafaelbn — APPROVED** [review]
Tested in runbot :+1:

**Comment by pedrobaeza** [comment]
We already discarded this fix, as it reduces visual ergonomy and the feature lack of multi-selection is solved with the other widget, so I close this.

**Pull request closed without merging**
