### PR TITLE
[15.0][IMP] account_financial_report: test multi-company

### PR DESCRIPTION
**Pull request by Tardo**
Without this correction the module fails in tests with modules that add demo data.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
The code of the test seems very fragile, but let's fix at least this one.

**Comment by pedrobaeza** [comment]
Ouch, check pre-commit

**Comment by Tardo** [comment]
Yes.. I always make the same mistake hehe sorry

fixed!

**Review by admingrupoisonores — APPROVED** [review]

**Review by jviares — APPROVED** [review]

**Pull request merged**
