### PR TITLE
[14.0][IMP] account_financial_report: Open Items reports also display residual currency in ending balance lines

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Review by michelerusti — APPROVED** [review]

**Comment by michelerusti** [comment]
LGTM!

**Comment by are-agilebg** [comment]
Review tecnica OK

**Review by are-agilebg — COMMENTED** [review]
Technical review OK

**Comment by tafaRU** [comment]
@OCA/accounting-maintainers could you please have a look at this?

**Pull request closed without merging**
