### PR TITLE
[FIX] iter_cell_tuples

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
In KpiMatrixCol, in iter_cell_tuples : fix the return sentence.

### CODE REVIEW

**Comment by ThomasBinsfeld** [comment]
@sbidoul @adrienpeiffer

**Comment by adrienpeiffer** [comment]
:+1: of course

**Comment by sbidoul** [comment]
Yes, this method is not used by mis_builder itself but it's needed for dependent module which reuse the computation algorithm.

:+1:

**Comment by sbidoul** [comment]
Fast tracking as it is not used by mis_builder and it's an obvious typo.

**Pull request merged**
