### PR TITLE
fix runbot warnings on 7.0

### PR DESCRIPTION
**Pull request by gurneyalex**
remove type field on ir.ui.view
replace groups field with groups_id on ir.ui.menu
remove object field on ir.values

### CODE REVIEW

**Comment by gurneyalex** [comment]
requesting a fast forward on this one to get nice green builds on PRs targetting 7.0

**Comment by PCatinean** [comment]
Neat cleanup :+1:

**Comment by bwrsandman** [comment]
Thank you for this cleanup :+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
