### PR TITLE
[FIX] webkit: trial balance fix migration bugs

### PR DESCRIPTION
**Pull request by sbidoul**
debit, credit and balance were always 0 in the webkit trial balance

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: Travis pending

**Comment by sbidoul** [comment]
Pushed a small commit, hoping to asymptotically converge to MQT nirvana.

**Comment by sbidoul** [comment]
and... green!

**Comment by lmignon** [comment]
:+1:

**Comment by anthony-muschang** [comment]
LGTM :+1:

**Pull request merged**
