### PR TITLE
[10][NEW] Account standard report

### PR DESCRIPTION
**Pull request by fmdl**
Dear

The Odoo report (community or entreprise) have lot of issues :
- Use different wizard to have different report
- Excel report is not Pivot Table compatible
- There are not some summary report
- Bad managing of matching number, for Odoo 9+ (continously accounting). 
- Bad managing of opening entries (initial balance)
- With this issue: https://github.com/odoo/odoo/issues/16925
- No openning journal
- No Journal report
- No total in partner report
- Some issue of localisation

This module solve lot of thing and make a better report (especially for excel).

### CODE REVIEW

**Comment by sbidoul** [comment]
Hello @fmdl,

Thanks for your contribution. 

By looking at the README it seems there is a lot of overlap with `account_financial_report_qweb` in this same repository. Have you considered using account_financial_report_qweb and possibility contributing missing features to that existing module?

**Comment by fmdl** [comment]
I understand what you said, but the big issue it was on the partner ledger with **unreconcillied only**, it is not available in Entreprise Edition, it is wrong in Community Edition, it is not available in`account_financial_report_qweb`. 
In Community Edition it is wrong because if you not compute the date of other entrie matched with, your ledger of last year change every time, because the matching number is over the years.

I was started on base made by @alnslang  : https://github.com/syleam/account_extra_report_partnerledger (which is a fork from Odoo), I was ported in V10 and fix the bug of matching number in the furtur (after the date range). After that I use this base to build the other repport (it is easy because, it is the same report but in different view). That why the main code is only 616 lines.

It is not realy excaltly the same, list of feature is missing in `account_financial_report_qweb`:
- Partner Ledger and Partner Trial Balance.
- Report excel ussable in pivot mode (1 line for 1 entries).
- Journal Ledger
- Différence in report if the entrie is matched with an other entrie including in date range or not
- Openning Trial balance
- Différence in report if the entrie is matched with an other entrie including in date range or not (* say it is reconcillied after the date range) :
image

Lets try, and come back.

**Comment by fclementic2c** [comment]
@fmdl 
Happy to get some valuable feedback/contribs on this topic.
However creating a new module for these reports instead of adding missing features on existing ones is: 1 - A huge job 
2 - We do not want 2 modules doing the same thing in one branch: so either the new module is far better and we might replace it OR it will not be into OCA branches hence not maintained by community.

Before you do so let's discuss weakness of account_financial_report_qweb.
So points are: 
< Lot of line of code (with lot of SQL script) : 
True and it was wanted (compares to previous version of the module) for performance reasons (some clients have millions of account_move_lines) and to avoid memory errors

Use different wizard to have different report
< True because we find it more clear for the end-user. You know that accountants have habits :)
Although, we merged (compares again to the previous version) the General ledger and Partner Ledger Wizard.

< Excel report is not Pivot Table compatible  (1 line for 1 entries).
What do you mean, to think of removing subtotals for ex. in order to get a pure list of move lines ?

< There are not some summary report
example please.

< Bad managing of matching number, for Odoo 9+ (continously accounting).
example please.
In Odoo, there is not archiving of previous fy. So you always see all entries.
So a payment in 2017 can be matched with an invoice posted in 2016.

< Bad managing of opening entries (initial balance)
With this issue: odoo/odoo#16925
This issues is solved with OCA module

< No render option (sum in top or bottom, ...)
ok

< No opening journal
No because computed on the fly by reports (thanks to account type : current year earning)

< No Journal report
ok but I doubt of the necessity of having this one.
(you can do a csv export + you have FEC export)
But it would be good having it.

< No total in partner report
You have that with OCA report

< Some issue of localisation
example please.

< Partner Ledger and Partner Trial Balance.
You have that with OCA report

< Différence in report if the entry is matched with an other entry including in date range or not
Opening Trial balance
You have that with OCA report (open items report + in the trial or partner balance you have a column initial balance)

< Différence in report if the entrie is matched with an other entrie including in date range or not (* say it is reconcillied after the date range) :
I think you did not get how it works in odoo about this.
Same comment than 'Bad managing of matching number' above.

Sorry for the long list but I hope it helps.

Frederic

**Comment by fmdl** [comment]
@fclementic2c 
Tanks for you feedback. I understand the position of OCA.
At the start my accountant need the partner ledger without reconcillied entrie. I use the Syleam module, but it works in 2016 because we have start Odoo in 2016, but in 2017 it doesn't work, because the entries renconcillied with entries in 2017, desapears in 2016 report (without reconcillied entrie, of course). I have made a fix. And just after, because the Odoo report is bad, I have add other report and excel.

< Lot of line of code (with lot of SQL script) :
True and it was wanted (compares to previous version of the module) for performance reasons (some clients have millions of account_move_lines) and to avoid memory errors
`I understand, why there lot of SQL.`

Use different wizard to have different report
< True because we find it more clear for the end-user. You know that accountants have habits :)
Although, we merged (compares again to the previous version) the General ledger and Partner Ledger Wizard.
`For my accountant and my financial director, she finds better. Period, accounts it is register for all ledger.`

< Excel report is not Pivot Table compatible (1 line for 1 entries).
What do you mean, to think of removing subtotals for ex. in order to get a pure list of move lines ?
```
Yes, a pure list of move lines, with filter feature :
```
image


< There are not some summary report
example please.
`Summary it is trial balance, not ?`

< Bad managing of matching number, for Odoo 9+ (continously accounting).
example please.
In Odoo, there is not archiving of previous fy. So you always see all entries.
So a payment in 2017 can be matched with an invoice posted in 2016.
`Same things of Bad managing of opening entries, when the range date is in 2016, an entrie reconcillied with an entrie in 2017, it is concidered as un-reconcilied in 2016.`

< Bad managing of opening entries (initial balance)
With this issue: odoo/odoo#16925
This issues is solved with OCA module
`Are you solve the issue with the start date, when the start date is not the start of fiscal year ? The compute of initial balance is not the same.`

< No render option (sum in top or bottom, ...)
ok

< No opening journal
No because computed on the fly by reports (thanks to account type : current year earning)
`yes, but some time the accountant need one (like for SAGE, CEGID, ..., I know it is not the reference but it is in use a lot.)`


< No Journal report
ok but I doubt of the necessity of having this one.
(you can do a csv export + you have FEC export)
But it would be good having it.
`and with, name of company, date range, it is better.`

< No total in partner report
You have that with OCA report

< Some issue of localisation
example please.
`I think the date is not in the format of user (that why Syleam rebuilt the module partner_ledger).`

< Partner Ledger and Partner Trial Balance.
You have that with OCA report
'OK, the partner ledger is merge with the generale ledger, but I don't find the partner summary (partner trial balance)'

< Différence in report if the entry is matched with an other entry including in date range or not
Opening Trial balance
You have that with OCA report (open items report + in the trial or partner balance you have a column initial balance)
`Yes, but if you print the partner ledger in 2016 with an entrie matched with an other in 2017, in OCA you see the matching number, but it is confuse because 'where is the other corresponding entrie ?' If there a hole with a maching number you don't know where is came. In my report when you see a matching number you can see all the entries link to this matching number (more easier to make verification). `

< Différence in report if the entrie is matched with an other entrie including in date range or not (* say it is reconcillied after the date range) :
I think you did not get how it works in odoo about this.
Same comment than 'Bad managing of matching number' above.
`Odoo see always the matching number.`

**The OCA report show all entries, you can not show only the unreconcillied entries for exemple (usefull to follow the payment of customer and vendor).**

**Comment by sbidoul** [comment]
@fmdl @fclementic2c I've difficulties summing up the discussion above.

I gather the missing features in the OCA general ledger reports are
- a flat export that is easy to filter in Excel
- an export that show unreconciled entries *at a given date in the past* (the Open Items reports already exists)

Is that correct? Anything else?

**Comment by fclementic2c** [comment]
@sbidoul I think this is more a lack of deep knowledge about odoo accounting balance forwarding to new fiscal year + what can do the oca module. 
It is not obvious at 1st glance...

**Comment by sbidoul** [comment]
@fclementic2c perhaps some more documentation needs to be written about the OCA reports. Still I feel @fmdl has some valid points, I just have difficulties to filter out the essential points where the OCA report need improvement.

**Comment by fclementic2c** [comment]
@fmdl @sbidoul Sure, don't get me wrong. Comments are of course valid but the Odoo 'logic' + the way we did the fi. reports are maybe too complex.
I always wanted to do doc but... lack of time. I'll give a try.
however, I still think initiating a brand new module is not justified.

**Comment by sbidoul** [comment]
> however, I still think initiating a brand new module is not justified.

Totally agree with that. We need to improve what we have.

**Comment by fmdl** [comment]
Please you can find the report in SQL generation.

**Comment by fmdl** [comment]
@sbidoul @fclementic2c Are you test this report ?

**Comment by feketemihai** [comment]
@fmdl did you test last version available of account_financial_report_qweb, it is mostly build like this, so see this as a duplicate of the work done there, i think we should focus on only one module for basic reporting, if you want to improve account_financial_report_qweb module, be my guest.

**Pull request closed without merging**
