### PR TITLE
[12.0][FIX]account_tax_balance: improved code allowing to translate previously missed terms

### PR DESCRIPTION
**Pull request by antonio-trey**
Some terms were not properly implemented for being translated, have been added the possibility of translating those terms.

### CODE REVIEW

**Review by rlizana — APPROVED** [review]
LGTM :+1:

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
No need to manually bump the module version. The bot can do it.

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Can you please fw-port it to upper versions?

**Comment by antonio-trey** [comment]
> No need to manually bump the module version. The bot can do it.
> 
> /ocabot merge nobump

Understood, thanks.

**Comment by antonio-trey** [comment]
> Can you please fw-port it to upper versions?

@pedrobaeza of course, no problem.

**Pull request merged**
