### PR TITLE
[FIX][7.0] Sum on wrong column

### PR DESCRIPTION
**Pull request by llacroix**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you put an example? I suppose that 8.0 version it's already affected, doesn't it?

**Comment by llacroix** [comment]
@pedrobaeza what do you mean by example? like a before/after file? I can check for V8

**Comment by llacroix** [comment]
Yes, the bug seems to affect the v8 too.

**Comment by pedrobaeza** [comment]
Yes, please, a before/after comparison that illustrates it

**Comment by bwrsandman** [comment]
:+1:

**Comment by llacroix** [comment]
@pedrobaeza  here
Before:
screenshot from 2015-03-12 10 44 53

After:
screenshot from 2015-03-12 10 41 11

**Comment by pedrobaeza** [comment]
But I'm seeing the same result in both...

**Comment by llacroix** [comment]
@pedrobaeza I highlighted the column that does the wrong calculation. As you can see, the sum is done on "Cummul. Bal." instead of "Curr. Balance". The sum for Curr Balance in the first picture gives 300 below. (71.9 + 143.8) = 215.70 != 300

**Comment by sbidoul** [comment]
Understood. :+1:

**Comment by pedrobaeza** [comment]
Ah, OK. Thanks for the explanation.

:+1:

**Comment by llacroix** [comment]
By the way, the number on the column that isn't present next to the formula is there, it just disappear when I select the cell. 

Here two more screenshots:

Before:
screenshot from 2015-03-12 11 45 53

After:
screenshot from 2015-03-12 11 45 27

**Comment by llacroix** [comment]
Thank you

**Pull request merged**
