### PR TITLE
[15.0][MIG] partner_statement

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Pre-commit will fail until #858 is merged.

Depends on:
 

- [x]  https://github.com/OCA/reporting-engine/pull/584

The check boxes to enable this module were inside "Customer Payments" in Invoicing/Settings, which was a bit confusing since this module is to print both customer and vendor statements. So I've put them under Partner Statements.

Added cherry-pick of https://github.com/OCA/account-financial-reporting/commit/009811ff751af3f84160921e0a4bdcf2005b680c and https://github.com/OCA/account-financial-reporting/commit/b63571341331f859620eb197f451a9c6ed83a608

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@mariadforgeflow can you rebase this one? dependency is merged.

**Comment by MiquelRForgeFlow** [comment]
@mariadforgeflow please rebase and cherry-pick 009811ff751af3f84160921e0a4bdcf2005b680c and b63571341331f859620eb197f451a9c6ed83a608 ;)

**Comment by gdgellatly** [comment]
I kind of disagree with the change of config classification. While this module *can* be used to print Vendor statements in practice they are not real statements (because that is what the vendor sends you). Its basically just a free feature.

The overwhelming usage of this module is for Customer statements.  The Vendor functionality from what I see users doing is only useful for doing things like manual reconciliations with vendors when they misapply prior payments. Basicaly a poor mans remittance over time.

What is the actual use case for needing regular Vendor statements?

**Comment by mariadforgeflow** [comment]
@gdgellatly In this case I did it like that because there has to be a cohesion between the module functionality and the settings. As it is explained in the readme, it can be used for any type of partner.
Taking into account that in the migration the functionality has to remain the same, I just moved it to have a concordance between how the module can be used and the definition in its settings. This being said, I understand that the main use of the module is for Customers Statements so I can leave it like it was before.

**Comment by gdgellatly** [comment]
@mariadforgeflow its not something i'd worry about. Customer payments is wrong anyway, as it isnt to do with payments.

**Comment by gdgellatly** [comment]
While we are renaming things, let's deal to #720 . Now personally I don't like Aging Statement, never heard it called that and just prefer either Statement or Statement of Account. But also Aging Statement is in itself problematic for no other reason than not all statements contain aging as it is an option.

\cc @AaronHForgeFlow

**Comment by AaronHForgeFlow** [comment]
@gdgellatly, I created that PR because of a US company told me that Aging Statement was the appropriate name. However, it is not clear to me what name it should be. Now it seems users are getting use to the current names so I would not change that for now.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by rafaelbn** [comment]
Please @kosaaaaa could you review this PR? The one you have done is duplicated with this one. Thank you! 😄

**Comment by MiquelRForgeFlow** [comment]
Please @mariadforgeflow cherry-pick https://github.com/OCA/account-financial-reporting/commit/22693cf160bc3af1bccfa3d45c963dbbdee78e8d

**Comment by rafaelbn** [comment]
@MiquelRForgeFlow @AaronHForgeFlow ready? 😄

**Review by etobella — APPROVED** [review]
Tested on runboat

**Comment by rafaelbn** [comment]
Hello @gdgellatly , could please continue conversation from https://github.com/OCA/account-financial-reporting/pull/859#issuecomment-1060651775 ? This PR is approved so will get merge soon. Thank you very much 😄

**Comment by rafaelbn** [comment]
@mariadforgeflow @AaronHForgeFlow take care of this issue https://github.com/OCA/account-financial-reporting/issues/872 if it is in v14 maybe also en v15

**Comment by gdgellatly** [comment]
> Hello @gdgellatly , could please continue conversation from [#859 (comment)](https://github.com/OCA/account-financial-reporting/pull/859#issuecomment-1060651775) ? This PR is approved so will get merge soon. Thank you very much smile

@rafaelbn there is nothing to continue. It was decided no change.

**Comment by AaronHForgeFlow** [comment]
There was an issue in v13, but according to the fixes done it 14.0 those must be fixed now. I will check.

**Review by AaronHForgeFlow — APPROVED** [review]
I did a functional review. It looks good to me and this issue is not present: https://github.com/OCA/account-financial-reporting/pull/857

**Pull request merged**
