### PR TITLE
[IMP][mis_builder] MIS Builder widget improvement, add print and export button in the widget.

### PR DESCRIPTION
**Pull request by adrienpeiffer**
In the Qweb file, I simply add a general div causing a large diff. I also added the two buttons.

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
Travis errors seems unrelated travis flake 8 errors ...

**Comment by adrienpeiffer** [comment]
Rebased

**Comment by sbidoul** [comment]
@adrienpeiffer can you rebase?

**Comment by adrienpeiffer** [comment]
it's done @sbidoul

**Comment by sbidoul** [comment]
This is needed to implement dynamic filters in preview and dashboard views. Example in #168.

This also open the door to easier embedding of the mis_builder widget in other views (such as a project view).

:+1: (code review and functional test)

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
