### PR TITLE
[FIX] travis wkhtmltopdf download url

### PR DESCRIPTION
**Pull request by yvaucher**
Fix travis build

Example of failed build: https://travis-ci.org/OCA/account-financial-reporting/builds/47941388

### CODE REVIEW

**Comment by sbidoul** [comment]
:+1: 

Do you confirm 0.12.2 does not work?

**Comment by pedrobaeza** [comment]
I think it's more a question of file accesibility, because the URL has changed.

:+1:

**Comment by sbidoul** [comment]
@pedrobaeza not only: 0.12.2 is there but has been reported to not work with Odoo.

**Comment by pedrobaeza** [comment]
I'm using it without problems...

**Comment by yvaucher** [comment]
No idea if 0.12.2 works but build are currently failing due to this. (updated description)

I'll do the same PR on 7.0

**Comment by Cedric-Pigeon** [comment]
Hi,

I tested 012.2 last week and I encountered some problems with footers. They are not printed.
I tested the Odoo Sale Order and Invoice.

@pedrobaeza  Are you sure your reports are well printed ?

**Comment by pedrobaeza** [comment]
I will try again and tell you back.

**Comment by guewen** [comment]
:+1: 
I merge this one to fix the url and if we see that  012.2 works, we can still make another PR

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza issue https://github.com/odoo/odoo/issues/5177 confirm my test about wkhtmltopdf 0.12.2

**Comment by pedrobaeza** [comment]
Yeah, I see. I was not awared of the footer thing, but yesterday I see also problems in one custom report (but not in the standard one), and now I see that it's due to the wkhtmltopdf version.

**Pull request merged**
