### PR TITLE
[13.0][MIG] partner_statement

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by gdgellatly — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@MiquelRForgeFlow Can you do a rebase to fix isort conflicts?? Thanks

**Comment by MiquelRForgeFlow** [comment]
@sergio-teruel done and ready

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests :+1:

**Pull request merged**
