### PR TITLE
[FIX] [8.0] Add reference field to account_financial_report_webkit_xls

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This fix adds the field 'Reference' associated to the account move line to 'account_financial_report_webkit_xls', so that the resulting layout matches with 'account_financial_report_webkit'.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I would put a little smaller the column. And now you're adding a column in between, so you need to move the totals one column right ("Cumulated Balance on Account" and so on).

seleccion_005

**Comment by JordiBForgeFlow** [comment]
Thanks @pedrobaeza. I fixed.

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by antespi** [comment]
:+1:

**Comment by ovnicraft** [comment]
Ready to merge ?

**Pull request merged**
