### PR TITLE
[MIG] account_tax_balance: Migration to 15.0 

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Depends to:
- [x]  https://github.com/OCA/server-ux/pull/414

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten

**Comment by HaraldPanten** [comment]
@ValentinVinagre date_range has already been merged. Could you rebase? THX

**Comment by pedrobaeza** [comment]
Please include #841

**Comment by ValentinVinagre** [comment]
@pedrobaeza @HaraldPanten done!

**Review by HaraldPanten — APPROVED** [review]
Functional review.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
