### PR TITLE
[14.0] [MIG] account_move_line_report_xls

### PR DESCRIPTION
**Pull request by PieterPaulussen**
Ported from 13.0 PR from @luc-demeyer https://github.com/OCA/account-financial-reporting/pull/666

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
* please squash the earlier commits by the original author
* please check travis (replace `render_xlsx` with `_render_xlsx` and next time, please check if the module tests succeed before filing the PR ;-)

**Review by rconjour — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]

**Review by hkapatel-initos — APPROVED** [review]
Did code review and functional test: LGTM

**Comment by hkapatel-initos** [comment]
Hello, @pedrobaeza can you please look at this pull?

**Comment by pedrobaeza** [comment]
Merging based on the reviews:

/ocabot merge nobump

**Pull request merged**
