### PR TITLE
[16.0][FIX] account_financial_report, Fix report links with domain

### LINKED ISSUE #1035: [16][BUG] account_finalcial_report In the Trial Balance, numerical data are not navigable
## Module
account_finalcial_report

## Describe the bug
In the Trial Balance, numerical data are not navigable
image

## To Reproduce
V16

1. Go to Invoicing/Reporting/Trial Balance
2. I run the wizard with the following options
image
3. The generated report does not allow navigation through the numerical data

**Expected behavior**
In V14/V15 this report work fine

### PR DESCRIPTION
**Pull request by ramiadavid**
Fix #1035 and fix warnings with deprecated t-raw in reports

### CODE REVIEW

**Comment by ramiadavid** [comment]
The report works but I'm trying to remove some errors that appear in the console

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @ramiadavid 

Captura desde 2023-04-28 10-39-06

**Review by loida-vm — APPROVED** [review]
Functional review done! 
image

LGTM! Thank you for your work!

**Comment by ramiadavid** [comment]
@pedrobaeza Hello, I have been reviewing the errors that I see in the console and it seems that they do not come from this module, maybe it is from another OCA or odoo module, but in any case since the report works I understand that this is not for this PR so that for my part it would be finished

image

**Review by rafaelbn — APPROVED** [review]
Tested 👍 

imagen

/ocabot merge patch

**Comment by rafaelbn** [comment]
@ramiadavid thank you very much! ❤️

**Pull request merged**
