### PR TITLE
fixes #36 - v8 account_financial_report_webkit error when print journal

### LINKED ISSUE #36: v8 account_financial_report_webkit error when print journal
/account_financial_report_webkit/report/print_journal.py", line 129, in set_context
    objects.sort(key=lambda a: (a.journal_id.code, a.period_id.date_start))
AttributeError: 'account.journal.period' object has no attribute 'sort'

### PR DESCRIPTION
**Pull request by ccarly**
Fix sort and moves in print_journal.py

### CODE REVIEW

**Comment by sbidoul** [comment]
Thanks for this PR. I have no time to test right now, but the change looks fine, so :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by joaoalf** [comment]
:+1: LGTM

**Comment by yvaucher** [comment]
This introduced few PEP8 issues :see_no_evil:

**Pull request merged**
