### PR TITLE
[10.0] Fix bug #252 Aged partner balance now works with user != admin

### PR DESCRIPTION
**Pull request by alexis-via**
Generate create_uid and create_date columns in table report_aged_partner_balance_qweb_line

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by alexis-via** [comment]
Pylint error seems unrelated. The other travis checks are green.

**Comment by alexis-via** [comment]
I checked all the INSERT INTO in the code of account_financial_report_qweb to make sure that they handle create_uid and create_date ; it's all good now.

**Comment by pedrobaeza** [comment]
This is the risk of manipulating directly SQL...

**Comment by wim-a** [comment]
Hello Alexis,
I tested this fix, and it works fine now.
Thanks a lot.
Best regards,
Wim

**Review by sbidoul — APPROVED** [review]
A productive Sunday evening @alexis-via :wink: 

Nice find!

**Review by yvaucher — APPROVED** [review]
Good catch, didn't know that missing create_uid, create_date would mess up with ACLs

**Pull request merged**
