### PR TITLE
[13.0][IMP] account_financial_report: Amount currency columns from general ledger.

### PR DESCRIPTION
**Pull request by victoralmau**
Changes done to general ledger:
- [x] Remove `Cur.` column (currency is now added in `Amount cur.`).
- [x] Add `Cumul cur.` column.

despues

Please @pedrobaeza and @sergio-teruel could you review it?

@Tecnativa TT38722

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The Excel export part is missing.

**Comment by victoralmau** [comment]
Changes done.

**Comment by pedrobaeza** [comment]
Please rebase when the other PR is merged.

**Comment by victoralmau** [comment]
Rebase done.

**Comment by pedrobaeza** [comment]
@victoralmau I keep getting the error:

<details>

```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/report_xlsx/controllers/main.py", line 39, in _report_routes_xlsx
    xlsx = report.with_context(context).render_xlsx(docids, data=data)[0]
  File "/mnt/data/odoo-addons-dir/account_financial_report/models/ir_actions_report.py", line 25, in render_xlsx
    return super(IrActionsReport, obj).render_xlsx(docids, data)
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/report_xlsx_helper/models/ir_actions_report.py", line 19, in render_xlsx
    return super(IrActionsReport, self).render_xlsx(docids, data)
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/report_xlsx/models/ir_report.py", line 22, in render_xlsx
    docids, data
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/report_xlsx/report/report_abstract_xlsx.py", line 105, in create_xlsx_report
    self.generate_xlsx_report(workbook, data, objs)
  File "/mnt/data/odoo-addons-dir/account_financial_report/report/abstract_report_xlsx.py", line 57, in generate_xlsx_report
    self._generate_report_content(workbook, report, data)
  File "/mnt/data/odoo-addons-dir/account_financial_report/report/general_ledger_xlsx.py", line 276, in _generate_report_content
    self.write_line_from_dict(line)
  File "/mnt/data/odoo-addons-dir/account_financial_report/report/abstract_report_xlsx.py", line 277, in write_line_from_dict
    format_amt = self._get_currency_amt_format_dict(line_dict)
  File "/mnt/data/odoo-addons-dir/account_financial_report/report/abstract_report_xlsx.py", line 490, in _get_currency_amt_format_dict
    format_amt.set_num_format(self._report_xlsx_format_amount(currency))
AttributeError: 'report.a_f_r.report_general_ledger_xlsx' object has no attribute '_report_xlsx_format_amount'
```

</details>

When I have at least an invoice with other currency. Can you please check?

**Comment by victoralmau** [comment]
Sorry, the function name (https://github.com/OCA/reporting-engine/pull/647) had not been updated here. It has been changed and tested.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
