### PR TITLE
[FIX] [7.0] Add reference field to account_financial_report_webkit_xls

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This fix adds the field 'Reference'  associated to the account move line to 'account_financial_report_webkit_xls', so that the resulting layout matches with  'account_financial_report_webkit'.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Same comments as in #107

**Comment by JordiBForgeFlow** [comment]
Thanks @pedrobaeza. Fixed that.

image

**Comment by pedrobaeza** [comment]
:+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by feketemihai** [comment]
@jbeficent Do you still need this for V7?

**Pull request closed without merging**
