### PR TITLE
8.0 fix pre_print_report account_financial_report_webkit

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@pedrobaeza 
I 'greenified' this PR yesterday but the runbot build doesn't execute. Anything I can do to deblock this situation ?

**Comment by pedrobaeza** [comment]
Runbot is broken with the change to Docker. Please be patient while it's been repaired, although the review process can continue offline or making code review. Reference: https://github.com/OCA/runbot-addons/issues/111

**Comment by moylop260** [comment]
For this case a `TESTS="1"` is required from `.travis.yml` file to add compatibility with runbot.

**Review by moylop260 — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@moylop260 
Thanks for your help.
Still one failing check. Anything I can do to pass also this check ?

**Comment by moylop260** [comment]
Codecov told us that we are not testing the part that changed 
But the changes are small then we can merge it
Waiting more approvals

**Review by pankk — APPROVED** [review]

**Comment by luc-demeyer** [comment]
minor change (primarily 'greenify') and two positive reviews.
I think this  PR is ready for merge.
Can someone do this ?

**Comment by sbidoul** [comment]
@luc-demeyer I resolved the conflict on .travis.yml. I'll merge when travis is happy. Thanks!

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
