### PR TITLE
[10.0][FIX] account_financial_report_qweb:  Link reconcile model instead just name 

### PR DESCRIPTION
**Pull request by i-vyshnevska**
Contains commits from [PR 508](https://github.com/OCA/account-financial-reporting/pull/508) to avoid failing on lint will be rebased after aprove

In report General Ledger have error on reconcile_id line 
mt_num

Fix error on amount currency sign 
bug

Improvements:
- the reconcile id, you can view the reconciled account move lines in tree view

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis errors.

**Comment by fclementic2c** [comment]
test ok :+1:

**Review by fclementic2c — APPROVED** [review]

**Comment by fclementic2c** [comment]
would be nice to add a blue color on the reconcile id so that end users understand that they can click on it

**Review by simahawk — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please forward-port it to v11

**Pull request merged**
