### PR TITLE
Correct Pylint warnings

### PR DESCRIPTION
**Pull request by guewen**
Supersedes this #27 with additional corrections:
- removed the extraneous line between class and docstring
- Fixed W0621 warnings and some W0622
- Removed print statements
- Removed a duplicated key in dictionary (_columns)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: waiting for Travis

**Comment by guewen** [comment]
Yes I wait for Travis because I am not sure that all is fixed, not setup pylint locally yet.

**Comment by tafaRU** [comment]
@guewen https://github.com/guewen/account-financial-reporting/pull/1 fixes flake8 errors.

**Comment by sbidoul** [comment]
:+1: LGTM

**Comment by tafaRU** [comment]
:+1: I proceed with the merge.

**Pull request merged**
