### PR TITLE
Migration of account_financial_report_qweb to 10.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**
- [x] Depends on https://github.com/OCA/reporting-engine/pull/76

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We must split first the XLSX export from the main module in 9.0 before migration.

**Comment by adrienpeiffer** [comment]
@pedrobaeza is there some discussion about this split ?

**Comment by pedrobaeza** [comment]
Yeah, I said it in https://github.com/OCA/account-financial-reporting/pull/219#r77776645 (when I tracked the problem)

**Comment by sbidoul** [comment]
If there are no volunteers right now to do this split, I suggest we migrate as is. Splitting can be done in another PR.

**Review by yvaucher — APPROVED** [review]

**Review by jgrandguillaume — APPROVED** [review]
Hi,

Thanks for the work, as Stéphane, I think we should merge it like this, the split can be done in a second time..

:+1: 

Regards,

Joël

**Comment by sbidoul** [comment]
@adrienpeiffer do you know why travis is red?

**Review by alexis-via — APPROVED** [review]

**Comment by adrienpeiffer** [comment]
@sbidoul it's green now :smile:

**Review by lmignon — APPROVED** [review]

**Comment by ovnicraft** [comment]
I have a doubt here, in v8 reports allow get general ledger per account without grouping by partner, i cant find the options to obtain this, was removed in v10 ?

**Comment by ovnicraft** [comment]
My fault, its present.

**Pull request merged**
