### PR TITLE
[10.0] FIX account_financial_report_qweb trial balance: consider journals set in wizard

### PR DESCRIPTION
**Pull request by eLBati**
See https://github.com/OCA/account-financial-reporting/issues/545

### CODE REVIEW

**Review by SimoRubi — CHANGES_REQUESTED** [review]
Thanks for the PR!
I just tried this in runbot and when generating the PDF (with a journal selected) this happens:
```
[...]
  File "/home/odoo/build/OCA/account-financial-reporting/account_financial_report_qweb/report/general_ledger.py", line 248, in compute_data_for_report
    self._inject_account_values()
  File "/home/odoo/build/OCA/account-financial-reporting/account_financial_report_qweb/report/general_ledger.py", line 624, in _inject_account_values
    self.env.cr.execute(query_inject_account, query_inject_account_params)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 60:                 ml.journal_id IN (1,)
```

**Comment by SimoRubi** [comment]
I've created https://github.com/eLBati/account-financial-reporting/pull/1 that fixes the above error, can you have a look?

**Comment by eLBati** [comment]
@SimoRubi thanks!

**Review by SimoRubi — APPROVED** [review]
Code review

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers can this be merged?

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
