### PR TITLE
german translations with higher coverage

### PR DESCRIPTION
**Pull request by rschnapka**
tried my best to get terms correct - fine tuning and adjustment in wording compared to main-steam modules (standard OpenERP/ODOO-Modules) might need follow-up work on either end. International financials and german apsects differ in some aspects. Wording and terminology are of course crucial here and should be dealt with carefully... collaboration would be greatly appreciated here.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Excellent work you're doing with the translations!

:+1:

**Comment by rschnapka** [comment]
thanks, it's fun and hopefully helpful too :-)

**Comment by pedrobaeza** [comment]
Indeed, I'm not german, but german-speaking people will thank you a lot.

**Comment by yvaucher** [comment]
Great work thanks :+1:

**Pull request merged**
