### PR TITLE
[12.0][IMP] partner_statement: Create test user without password to avoid crash tests with other modules like as password_security

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT19500
Review @chienandalu @carlosdauden

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
If CIs go well :+1:

**Review by pedrobaeza — APPROVED** [review]
I'm going to fast-track this as straight-forward.

**Comment by pedrobaeza** [comment]
After fixing translations in other module in 58ada06586c804700cf806a124a24d404171fdb8

/ocabot merge patch

**Pull request merged**
