### PR TITLE
[16.0][IMP][account_financial_report]: add custom intervals for aged partner report

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
Fw port to v16 https://github.com/OCA/account-financial-reporting/pull/1083

@Tecnativa
TT45574

@pilarvargas-tecnativa @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check on http://oca-account-financial-reporting-16-0-pr1140-89edc2c57739.runboat.odoo-community.org, filtering the aged report by the partner "Test customer", and putting the reference date at 04/18/2024 (English US date format). It should be in the column "30", but it appears in the column "2".

**Comment by pedrobaeza** [comment]
@carolinafernandez-tecnativa please check the error I reported.

**Comment by carolinafernandez-tecnativa** [comment]
> @carolinafernandez-tecnativa please check the error I reported.

Coud you please check it now? thanks

**Review by pedrobaeza — APPROVED** [review]
OK, finally. Please backport the latest patch and fw-port the full feature to 17.0

**Comment by pilarvargas-tecnativa** [comment]
Can you remove the "or" between the buttons?
https://github.com/OCA/account-financial-reporting/blob/6912cb9418153875eb2ab20dbb8272dc52862c55/account_financial_report/wizard/aged_partner_balance_wizard_view.xml#L65-L87

image

**Comment by carolinafernandez-tecnativa** [comment]
> Can you remove the "or" between the buttons?
> 
> https://github.com/OCA/account-financial-reporting/blob/6912cb9418153875eb2ab20dbb8272dc52862c55/account_financial_report/wizard/aged_partner_balance_wizard_view.xml#L65-L87
> 
> image

Done Thanks :)

**Comment by carolinafernandez-tecnativa** [comment]
> OK, finally. Please backport the latest patch and fw-port the full feature to 17.0

1- Fw to V17 https://github.com/OCA/account-financial-reporting/pull/1147
2- Backport the lastest patch https://github.com/OCA/account-financial-reporting/pull/1146

**Comment by pilarvargas-tecnativa** [comment]
In the interval of less than 1 day, no overdue invoice ever appears. Creating an invoice due today and another due tomorrow. The report is output with today's date, the invoice due yesterday is placed in the next interval. In the same way, if a report is drawn with tomorrow's date, the invoice due today also appears in the next interval. In this way the 1 day interval will never contain overdue invoices.

image
image
image

**Comment by pedrobaeza** [comment]
cc @carolinafernandez-tecnativa

**Comment by carolinafernandez-tecnativa** [comment]
> In the interval of less than 1 day, no overdue invoice ever appears. Creating an invoice due today and another due tomorrow. The report is output with today's date, the invoice due yesterday is placed in the next interval. In the same way, if a report is drawn with tomorrow's date, the invoice due today also appears in the next interval. In this way the 1 day interval will never contain overdue invoices.
> 
> image image image

Ready for review Thanks

**Comment by pilarvargas-tecnativa** [comment]
I have 4 invoices: one is due today (22/04/2024 not due), one is due yesterday (21/04/2024 1 day), one is due 5 days ago and one is due 10 days ago.
image

Aged Partner Balance on 22/04/2024 is correct:
image

Aged Partner Balance on 04/23/2024 is not correct as the invoice due yesterday (04/21/2024) is a limit less than 5 and appears at 1:

image

In addition the following limits should appear so that the one that the invoice due in 5 days on 22/04/2014 on 23/04/2024 should appear in limit less than 10 and the one due in 10 days should no longer appear.

Aged Partner Balance on 24/04/2024 and 25/04/2024 is incorrect too:

image

Could it be that the wizard is not taking the date correctly to calculate the number of days?

**Review by pilarvargas-tecnativa — APPROVED** [review]
Functionality is correct, thank you! :smile:

**Pull request merged**
