### PR TITLE
[11][account_financial_report] trial balance: remove account groups if hierarchy = 'none'

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @rafaelbn @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Thanks :+1:

**Comment by rafaelbn** [comment]
Be aware that bots are :red_circle:

**Comment by JordiBForgeFlow** [comment]
@rafaelbn they are green. I think that the push line can be ignored, right @pedrobaeza

**Comment by pedrobaeza** [comment]
Yes, fast-tracking this

**Pull request merged**
