### PR TITLE
[13.0][FIX] account_financial_report: Print report with details

### LINKED ISSUE #808: [13.0][BUG] account_financial_report, error Aged Partner Balance with Show move line details
Just install module with demo database, and run Aged partner Balance report.

Affected version: 13.0.1.8.0 (latest)

image

image

image

### PR DESCRIPTION
**Pull request by SimoRubi**
Backporting https://github.com/OCA/account-financial-reporting/pull/809, this fixes https://github.com/OCA/account-financial-reporting/issues/808

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please pass black formatting

**Comment by SimoRubi** [comment]
> Please pass black formatting

Yes I'm checking it but there is a conflict between black that is asking for:
```
         wizard = self.wizard_model.create(
-            {
-                "show_move_line_details": True,
-                "receivable_accounts_only": True,
-            }
+            {"show_move_line_details": True, "receivable_accounts_only": True,}
         )
```
and flake8 that with such correction asks for:
```
account_financial_report/tests/test_aged_partner_balance.py:16:78: E231 missing whitespace after ','
```
when I add the missing whitespace, then black reformats etc...
I'm looking for a solution to this loop (that's why this is still in draft)

**Comment by pedrobaeza** [comment]
Remove last comma

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers can this be merged?
Thanks!

**Review by joao-p-marques — APPROVED** [review]
LGTM 👍 

However, could you put the pre-commit changes in the same commit? I think it would make more sense here…

**Comment by SimoRubi** [comment]
> LGTM 
> 
> However, could you put the pre-commit changes in the same commit? I think it would make more sense here…

Thanks for the review, I originally kept them separated because the first one was the clean `cherry-pick` and the other one just _linter's stuff_; anyway now they are squashed.

**Comment by joao-p-marques** [comment]
Thanks! I think that is clearer, as having a separate commit is more for big changes, when migrating, for example...

**Pull request merged**
