### PR TITLE
[DEL] oca_dependencies: remove duplicities

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
:S

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Better to put shortest definition.

**Comment by MiquelRForgeFlow** [comment]
Why?

**Comment by pedrobaeza** [comment]
Because it's more readable

**Comment by MiquelRForgeFlow** [comment]
Done

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this

**Pull request merged**
