### PR TITLE
10.0 imp account financial report qweb

### PR DESCRIPTION
**Pull request by mpanarin**
Allows filtering by account journal in general ledger and trial balance

### CODE REVIEW

**Review by fclementic2c — APPROVED** [review]

**Comment by mpanarin** [comment]
@pedrobaeza updated as well

**Review by pedrobaeza — APPROVED** [review]

**Comment by alexis-via** [comment]
The layout of the trial balance wizard view is broken now, cf screenshot.
trial_view_broken_layout

**Comment by alexis-via** [comment]
I'm preparing a PR to fix all this...

**Comment by alexis-via** [comment]
So I fixed the view breakage here: https://github.com/OCA/account-financial-reporting/pull/460

**Pull request merged**
