### PR TITLE
8.0 mis_builder: fix use of api.constrains

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by gurneyalex** [comment]
api.constrains methods must raise openerp.exception.Warning when the constraint is not met. 

cc @sbidoul

**Comment by sbidoul** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by sbidoul** [comment]
@gurneyalex I notice you made this PR against 9.0. Can you do it on 8.0 too?

**Pull request merged**
