### PR TITLE
[11.0][customer_activity_statement] extend to display receivables and payables

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
It is straightforward to provide the option to display also the payables of a partner. A pitty that the report was not named partner_activity_statement....

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on local and working as expected

**Comment by pedrobaeza** [comment]
If you change the scope, shouldn't the module should be partner_activity_statement?

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza but perhaps it's better to rename the module in version 12?

**Review by etobella — APPROVED** [review]
Function test ok on runbot :+1:

**Comment by pedrobaeza** [comment]
Please take note on the README then

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza  done

**Pull request merged**
