### PR TITLE
12.0 FIX account_export_csv: test the number of lines of the file

### PR DESCRIPTION
**Pull request by bealdav**
Without this fix, report has only 1 line

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM

**Comment by bealdav** [comment]
Please @cubells could you have a look here ?

**Comment by bealdav** [comment]
Please @sbidoul could you check here ?

**Review by alexis-via — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request closed without merging**
