### PR TITLE
[IMP] mis_builder: removed unused argument

### PR DESCRIPTION
**Pull request by sbidoul**
Was forgotten in 53192385fb67590b83ae0f425b7ed7dda49f4a35

The company is now part of AEP properties.

### CODE REVIEW

**Comment by sbidoul** [comment]
@adrienpeiffer @ThomasBinsfeld

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by ThomasBinsfeld** [comment]
:+1:

**Comment by lepistone** [comment]
ok! 👍

**Pull request merged**
