### PR TITLE
[IMP] mis_builder: meaningful copy for MIS Report templates

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by laetitia-gangloff** [comment]
Is it possible to do the same for report instance ? (copy of periods (compare with column))

**Comment by sbidoul** [comment]
@laetitia-gangloff yes, in another PR.

**Comment by laetitia-gangloff** [comment]
Ook :+1:

**Pull request merged**
