### PR TITLE
[13.0][partner_statement][IMP] email an statement directly to customer

### PR DESCRIPTION
**Pull request by shawr**
[13.0][partner_statement][IMP] Add the ability to email an statement directly to customer. I thought I'd contribute what we have used internally, I've tried to follow the OCA Guidelines, please let me know if I have missed something.

### CODE REVIEW

**Comment by enigmista91** [comment]
hi, I advise you follow the coding guideline https://www.odoo.com/documentation/15.0/contributing/development/coding_guidelines.html

and use the commmit message like [FIX] for bug fixes: mostly used in stable version but also valid if you are fixing a recent bug in development version;

[REF] for refactoring: when a feature is heavily rewritten;

[ADD] for adding new modules;

[REM] for removing resources: removing dead code, removing views, removing modules, …;

[REV] for reverting commits: if a commit causes issues or is not wanted reverting it is done using this tag;

[MOV] for moving files: use git move and do not change content of moved file otherwise Git may loose track and history of the file; also used when moving code from one file to another;

[REL] for release commits: new major or minor stable versions;

[IMP] for improvements: most of the changes done in development version are incremental improvements not related to another tag;

[MERGE] for merge commits: used in forward port of bug fixes but also as main commit for feature involving several separated commits;

[CLA] for signing the Odoo Individual Contributor License;

[I18N] for changes in translation files;

[type][module] message of commit

**Comment by shawr** [comment]
> hi, I advise you follow the coding guideline https://www.odoo.com/documentation/15.0/contributing/development/coding_guidelines.html
> 
> and use the commmit message like [FIX] for bug fixes: mostly used in stable version but also valid if you are fixing a recent bug in development version;
> 
> [REF] for refactoring: when a feature is heavily rewritten;
> 
> [ADD] for adding new modules;
> 
> [REM] for removing resources: removing dead code, removing views, removing modules, …;
> 
> [REV] for reverting commits: if a commit causes issues or is not wanted reverting it is done using this tag;
> 
> [MOV] for moving files: use git move and do not change content of moved file otherwise Git may loose track and history of the file; also used when moving code from one file to another;
> 
> [REL] for release commits: new major or minor stable versions;
> 
> [IMP] for improvements: most of the changes done in development version are incremental improvements not related to another tag;
> 
> [MERGE] for merge commits: used in forward port of bug fixes but also as main commit for feature involving several separated commits;
> 
> [CLA] for signing the Odoo Individual Contributor License;
> 
> [I18N] for changes in translation files;
> 
> [type][module] message of commit

I shall squash the commits, and make them fit the commit standard

**Comment by matteoopenf** [comment]
On commit you should add the name of module between [], squash all in one commit.
I Will start a review

**Comment by shawr** [comment]
> On commit you should add the name of module between [], squash all in one commit. I Will start a review

any progress?

**Comment by matteoopenf** [comment]
> > On commit you should add the name of module between [], squash all in one commit. I Will start a review
> 
> any progress?

if you don't change the commit the review not start

**Pull request closed without merging**
