### PR TITLE
[13.0][FIX] account_sale_stock_report_non_billed: Date can't be comparated with bool

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT40573

ping @sergio-teruel @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe a regression test?

**Review by pedrobaeza — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@CarlosRoca13 Don't forget to port the changes to future versions when the PR has been merged

**Pull request merged**
