### PR TITLE
[IMP][mis_builder] Improve usability : Display directly report instance instead of report instance settings.

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Currently on mis.report.instance list view, when the user click on a mis.report.instance that open a form which mise.report.instance configuration. This PR changes this behavior to open directly the report (Currently, this is the preview). It also adds a button on mis.report.instance list to directly access to the parameters.

### CODE REVIEW

**Comment by sbidoul** [comment]
Very cool usability improvement! Nitpicking: a small whitespace between the buttons and the table header would be nicer.

image

**Comment by alexis-via** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
@sbidoul It's done ! Thanks !

**Comment by laetitia-gangloff** [comment]
What do you think to set group : account.group_account_user on button "Settings" ?

Mis report can be set in dashboard and many user can access it, employee access is sufficient to see it.

**Comment by adrienpeiffer** [comment]
@laetitia-gangloff it's done ! Thanks !

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by sbidoul** [comment]
@adrienpeiffer works fine now. 

:+1: 

Ready to merge IMO.

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
