### PR TITLE
[14.0][FIX] account_financial_report: fix VAT report template

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/account-financial-reporting/pull/773.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
The error is unrelated. Its due to https://github.com/odoo/odoo/commit/fcaa54939e9a4f0dd5e47cd0ccffe7aa24bd451c.

**Review by HaraldPanten — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Now with this, the 14.0 branch is greenified :)

**Comment by MiquelRForgeFlow** [comment]
Can we merge this to greenify the repo?

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
