### PR TITLE
[11.0][ADD] account_financial_report: make responsive reports

### PR DESCRIPTION
**Pull request by rgarnau**
This PR makes the OCA accounting reports responsive.

cc @jbeficent

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
We are unable to test qweb reports in v11:
https://github.com/Eficent/account-financial-reporting/blob/11.0-add-responsive-reports/account_financial_report/tests/abstract_test.py#L259
https://github.com/Eficent/account-financial-reporting/blob/11.0-add-responsive-reports/account_financial_report/tests/abstract_test.py#L230

It works testing XLSX.

Any suggestion? @pedrobaeza

**Comment by feketemihai** [comment]
@jbeficent @rgarnau I follow the same logic on romanian report D300, and changed the tests of report generation, and it passed CI, please see:

https://github.com/feketemihai/l10n-romania-1/blob/edfe7c264a58d0e9bc29242720aa33f319d0ca0d/l10n_ro_report_D300/tests/abstract_test.py#L35

**Comment by feketemihai** [comment]
@rgarnau I think you have to remove the methods: test_01_generation_report... it's already done by the test_reports.try_report..i only leave the html one...but remove pdf and xlsx...

**Comment by feketemihai** [comment]
@rgarnau This should stay : def test_02_generation_report_html(self):

**Comment by rgarnau** [comment]
@feketemihai Thank you!

**Comment by feketemihai** [comment]
@rgarnau Hope it will pass...

**Comment by feketemihai** [comment]
@rgarnau Also i remember that i changed inheritance of templates from web.layout to web.html_container
https://github.com/feketemihai/l10n-romania-1/blob/edfe7c264a58d0e9bc29242720aa33f319d0ca0d/l10n_ro_report_D300/views/l10n_ro_report_d300.xml#L5

**Comment by rgarnau** [comment]
@feketemihai Yeah, that's how it was at the beginning but I wanted to use the web.layout in order to make the reports responsive. Do you think web.layout is not working fine?

**Comment by feketemihai** [comment]
@rgarnau, even with html_container, it will make it responsive, but it seems that inheritance of the web.layout is something wrong with the csrf_token script...

**Comment by feketemihai** [comment]
And html_container is already calling report template parameters:
https://github.com/odoo/odoo/blob/1df6f4c74151d012f9ff784cef6eea58a5ac3b9e/addons/web/views/report_templates.xml#L44

**Comment by rgarnau** [comment]
@feketemihai - you are right! just tried and it works perfectly! Let's see if it passes the tests now :) Thank you very much for your help! :+1:

**Comment by feketemihai** [comment]
@rgarnau No problem, after pr PR will be merged, probably i will make another one to complete all the link to different models in the report, meaning to open accounts, journals, moves, ...

**Comment by rgarnau** [comment]
@feketemihai Okay! That'd be nice!

**Review by feketemihai — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
Thanks for your help @feketemihai !!

**Pull request merged**
