### PR TITLE
[IMP] Added the function to export the journal report to xls

### PR DESCRIPTION
**Pull request by fedexin40**
In the wizar of Journal was added the function to export the repot to xls like the other reports such as general ledger or open invoice and on so on. In the module account_financial_report_webkit_xls

### CODE REVIEW

**Comment by gurneyalex** [comment]
@fedexin40: who is federico who was flagged by the CLA bot?

**Comment by gurneyalex** [comment]
@fedexin40 could you please:
1. rebase your PR so that the recent fixes for runbot are available
2. add an automated test exercising the wizard

Thanks

**Comment by damendieta** [comment]
Hi, it seems that this PR is abandoned, can it be closed?. There is any reason to keep it open?...

Daniel.

**Comment by fedexin40** [comment]
Hello

Well yes it was abandoned, but I am going to work in it again, when I pushed the first job I didn't have idea about how to do all what @gurneyalex asked me, now so so.

**Comment by damendieta** [comment]
@fedexin40 nice, maybe it's better if you can do it for v9-v10 instead of v7... do you need it for v7?

**Comment by gurneyalex** [comment]
note : runbot uses the branch name to find the targetted odoo version.  it expects the name to be <odooversion>-<description>. In this case, since the name of your branch does not start with "7.0-" it is confused and you are guaranteed to get a red runbot build.

**Comment by pedrobaeza** [comment]
Will anyone work on this or should we close it?

**Comment by feketemihai** [comment]
@fedexin40 I will close one since no activity for a long time. Please reopen it if still need it.

**Pull request closed without merging**
