### PR TITLE
translation / context in browse

### PR DESCRIPTION
**Pull request by BT-ojossen**
added translation file for de
added context in browse of account.account call

### CODE REVIEW

**Comment by yvaucher** [comment]
Few pep8 to fix. Max 79 char per line

```
./account_financial_report_webkit/report/partners_ledger.py:152:80: E501 line too long (84 > 79 characters)
./account_financial_report_webkit/report/open_invoices.py:151:80: E501 line too long (84 > 79 characters)
./account_financial_report_webkit/report/general_ledger.py:125:80: E501 line too long (84 > 79 characters)
./account_financial_report_webkit/report/common_partner_balance_reports.py:284:80: E501 line too long (84 > 79 characters)
./account_financial_report_webkit/report/common_balance_reports.py:282:80: E501 line too long (84 > 79 characters)
./account_financial_report_webkit/report/common_reports.py:427:80: E501 line too long (86 > 79 characters)
```

**Comment by luc-demeyer** [comment]
I ,think this PR should be closed since
- translation of  po file is done via PR https://github.com/OCA/account-financial-reporting/pull/119
- the code to pass the context is not correct, cf.

**Comment by luc-demeyer** [comment]
I ,think this PR should be closed since
- translation of po file is done via PR #119
- the code to pass the context is not correct, cf.PR https://github.com/OCA/account-financial-reporting/pull/123

**Comment by BT-ojossen** [comment]
closed because duplicated with #121

**Pull request closed without merging**
