### PR TITLE
[10.0][mis_builder] Migration of mis_builder_analytic_filter to 10.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**
- [x] Forward modification on https://github.com/OCA/account-financial-reporting/pull/233
- [x] Depends on https://github.com/OCA/account-financial-reporting/pull/239

### CODE REVIEW

**Comment by sbidoul** [comment]
@adrienpeiffer suggestion: filter by analytic tag

**Comment by benwillig** [comment]
This PR can be closed as it was duplicated in https://github.com/OCA/mis-builder/pull/24, right?

**Comment by jalzaga** [comment]
What is the status of analytic filters for 10.0. Can we contribute to test?

**Comment by adrienpeiffer** [comment]
Hi,
In the version 10.0, we integrated the analyic filter directly in the mis_builder module in https://github.com/OCA/mis-builder/pull/24. You can test it directly on runbot. The link is at the bottom of the PR. I'll close this one.

**Pull request closed without merging**
