### PR TITLE
Quote all text to prevent false cell split in Excel

### PR DESCRIPTION
**Pull request by vrenaville**
Some customer have problem if a line contains TAB or other separator

### CODE REVIEW

**Comment by sbidoul** [comment]
@vrenaville 

:+1: , but you may want to finish the description "Some customer have problem if a line contain...".

**Comment by elicoidal** [comment]
:+1: 
What about travis?

**Comment by vrenaville** [comment]
@sbidoul indeed some characters were lost :)

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Merging and solving the Travis problem later.

**Comment by pedrobaeza** [comment]
Travis fix in https://github.com/OCA/account-financial-reporting/pull/176

**Pull request merged**
