### PR TITLE
[FIX] Change trigger of last_rec_date.

### PR DESCRIPTION
**Pull request by adrienpeiffer**
last_rec_date should be recomputed with reconciliation_id and reconciliation_partial_id

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,

LGTM :+1: 

Regards

**Comment by adrienpeiffer** [comment]
Thanks @jgrandguillaume !

Any other reviews?

**Comment by guewen** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
Thanks @guewen !

**Pull request merged**
