### PR TITLE
[IMP] account_tax_balance: add index

### PR DESCRIPTION
**Pull request by sbidoul**
This indexes improve the display time of
account_tax_balance by a factor of 10 on a database
with 1M move lines.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this is now best done in post_init_hook, but you will need to call it also from a migration script.

Please change also version number.

**Comment by sbidoul** [comment]
@pedrobaeza version bumped.

Why should I use post_init_hook or a migration script? The index creation is properly applied with a -u so it looks ok to me.

**Comment by pedrobaeza** [comment]
It's for avoiding that this code is executed each time you run the server, which happens using `init`.

**Comment by JordiBForgeFlow** [comment]
I agree with @pedrobaeza. We have plenty of examples in OCA of an init hook
that is called also by a migratiln script

**Comment by sbidoul** [comment]
@pedrobaeza @jbeficent, performance, seriously? The test for the index existence takes something like 150 microseconds during server startup. And it's done like this everywhere in Odoo.

**Comment by pedrobaeza** [comment]
Well, this is the kind of analysis you have made me in the other PR, but OK to let it as is.

Just remember that summing all these operations in `init` of each installed module can suppose an slower startup time. And although Odoo does it, it can be a mix of old inheritance because `post_init_hook` didn't exist previously and bad practices.

**Comment by JordiBForgeFlow** [comment]
Oh, so indexes are created in the init. Was not aware of that.

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
@pedrobaeza @jbeficent I'm curious now. I did a quick test and it seems to me `init()` runs with -u or -i but *not* during normal server startup. Its docstring says it runs after `_auto_init` which runs during -u/-i, right? Do I miss something?

**Comment by sbidoul** [comment]
@Cedric-Pigeon @adrienpeiffer You probably need this.

**Comment by pedrobaeza** [comment]
@sbidoul you are totally right! The method is only called on upgrades, not each time you restart server. I have been avoiding this since a long time for this bad assumption. Crystal clear now.

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by sbidoul** [comment]
@pedrobaeza So, post_init_hook + migration is for very heavy operations that we don't want to run during each -u, correct?

**Comment by pedrobaeza** [comment]
Well, the main difference is that `post_init_hook` is only run once: when installing module. The `init` method instead is called each time you make `-u` or `-i`, so it's acceptable to include these operations here. Of course, heavy operations can't be done each time you upgrade.

As side note, check the new module LasLabs and we have been cooking for autoupdating modules: https://github.com/OCA/server-tools/tree/10.0/module_auto_update

**Comment by JordiBForgeFlow** [comment]
I guess that we can merge this one now.

**Review by adrienpeiffer — APPROVED** [review]

**Pull request merged**
