### PR TITLE
[7.0] Improve Aged Partner Balance report

### PR DESCRIPTION
**Pull request by Ehtaga**
- Add a boolean that allow the user to generate an aged partner balance report with invoice details #76 
- Allow the user to choose the aging method : from Due Date (default) or Invoice Date #114 

Pdf with invoice details:
aged_partner_balance

### CODE REVIEW

**Comment by max3903** [comment]
Tested on runbot
:+1:

**Comment by max3903** [comment]
ping @jgrandguillaume

**Comment by fclementic2c** [comment]
:+1:

**Comment by fclementic2c** [comment]
@guewen @gurneyalex  any time for a review, thxs ? It is a really usefull feature for accountants.

**Comment by nmoturi** [comment]
The ageing seems to ignoring the transactions prior fiscal year if run with date option, I believe when the date option from and to is selected it needs to consider all the open invoices in that range, Ideally when date option is selected it need to have only one field "as at date"

**Pull request merged**
