### PR TITLE
[14.0][IMP] account_financial_report: Amount currency columns from general ledger.

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 13.0: https://github.com/OCA/account-financial-reporting/pull/898

Changes done to general ledger:
- [x] Remove `Cur.` column (currency is now added in `Amount cur.`).
- [x] Add `Cumul cur.` column.

divisa-pdf
divisa-excel

Please @pedrobaeza and @sergio-teruel could you review it?

@Tecnativa TT38722

### CODE REVIEW

**Comment by victoralmau** [comment]
In v14, the display of the data in the new columns changes:
ejemplo-v14

The currency is always set, therefore, the cell value is filled in, what changes do you think should be applied?

**Comment by pedrobaeza** [comment]
What about displaying content only if the currency of the aml is different from the company currency?

**Comment by victoralmau** [comment]
Added a new commit to show the value if the currency is different from the company's currency.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The accumulated currency column is summing everything, not only those with different currency.

**Comment by victoralmau** [comment]
> The accumulated currency column is summing everything, not only those with different currency.

Ok, I see, that was only happening in PDF report, it's changed now.
divisa-pdf

**Review by pedrobaeza — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
