### PR TITLE
12.0 mig account financial report date range

### PR DESCRIPTION
**Pull request by ntsirintanis**
Migrating account_financial_report_date_range from 11.0 to 12.0

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! Can you check this module's tests? It looks like travis breaks on them
```
`   File "/home/travis/build/OCA/account-financial-reporting/account_financial_report_date_range/tests/test_accounting_report.py", line 23, in test_accounting_report

`     'account.account_financial_report_balancesheet0')

`   File "/home/travis/OCB-12.0/odoo/api.py", line 864, in ref

`     return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)

`   File "/home/travis/OCB-12.0/odoo/addons/base/models/ir_model.py", line 1443, in xmlid_to_object

`     t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)

`   File "/home/travis/OCB-12.0/odoo/addons/base/models/ir_model.py", line 1427, in xmlid_to_res_model_res_id

`     return self.xmlid_lookup(xmlid)[1:3]

`   File "<decorator-gen-25>", line 2, in xmlid_lookup

`   File "/home/travis/OCB-12.0/odoo/tools/cache.py", line 93, in lookup

`     value = d[key] = self.method(*args, **kwargs)

`   File "/home/travis/OCB-12.0/odoo/addons/base/models/ir_model.py", line 1416, in xmlid_lookup

`     raise ValueError('External ID not found in the system: %s' % xmlid)

` ValueError: External ID not found in the system: account.account_financial_report_balancesheet0
```

**Comment by pedrobaeza** [comment]
Odoo doesn't include in v12 financial reports, so this doesn't have too much sense IMO.

**Comment by houssine78** [comment]
@ntsirintanis any chance to take the remark of @StefanRijnhart into account ? Just let us know if we need to go ahead with another PR to have this module merged.

**Comment by houssine78** [comment]
@pedrobaeza the module has been merged into financial-tools on v13 so I imagine it makes sense to have it on 12.0 or I missed something ?

**Comment by luc-demeyer** [comment]
Odoo dropped the financial reports based upon the 'account.financial.report' model as from V12 hence I don't we should migrate this one to 12.0.
@houssine78 
can you clarify your question "the module has been merged into financial-tools on v13 so I imagine it makes sense to have it on 12.0 or I missed something ?". Which module has been merged into financial-tools v13 ?

**Comment by houssine78** [comment]
@luc-demeyer ok I got mislead. A looked after it through the app store (which was on 10.0) and I felt on the 13.0 branch.

**Pull request closed without merging**
