### PR TITLE
[10.0][MIG] account_financial_report_horizontal

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Travis configuration is wrong:

image

**Comment by MiquelRForgeFlow** [comment]
Ok, but that Travis update can be done in another PR.

**Comment by MiquelRForgeFlow** [comment]
@aheficent Travis configuration is fixed now.

PR rebased.

**Review by hbrunn — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional + soft code review

**Comment by hbrunn** [comment]
I just notice this just gives me duplicate column on runbot: 
[Financial report.pdf](https://github.com/OCA/account-financial-reporting/files/2103119/Financial.report.pdf)

is this a known problem or am I missing some configuration?

**Comment by MiquelRForgeFlow** [comment]
Unknown problem it seems.

**Comment by hbrunn** [comment]
thanks for the reply, this is caused by changes in the account types. As I don't think we should be changing them, I came up with #438 - another alternative would be to just add a selection left/right for reports, then the user can configure it on her own

**Pull request merged**
