### PR TITLE
[FIX] afr_webkit sorting issue

### LINKED ISSUE #36: v8 account_financial_report_webkit error when print journal
/account_financial_report_webkit/report/print_journal.py", line 129, in set_context
    objects.sort(key=lambda a: (a.journal_id.code, a.period_id.date_start))
AttributeError: 'account.journal.period' object has no attribute 'sort'

### PR DESCRIPTION
**Pull request by sbidoul**
Should fix #36

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
I don't know if it is relevant here but in v8 you can call a `sorted()` method on `recordsets`: https://www.odoo.com/documentation/8.0/reference/orm.html#openerp.models.Model.sorted
The advantage is that it returns back a `recordset` and not a list.

**Comment by sbidoul** [comment]
@guewen that is definitely relevant. Thanks for the tip. That is only part of the solution, though.

**Comment by lmignon** [comment]
:+1: although I have not found a trace of the error on RunBot

**Comment by pedrobaeza** [comment]
A rebase is needed

**Comment by sbidoul** [comment]
This one is superseeded by #49

**Pull request closed without merging**
