### PR TITLE
[7.0][FIX] Line overlap

### PR DESCRIPTION
**Pull request by mileo**
overlap

### CODE REVIEW

**Comment by gurneyalex** [comment]
My PR fixing the runbot build on the 7.0 branch was recently merged. Can you rebase your PR?

**Comment by mileo** [comment]
@gurneyalex done! =D

**Comment by pedrobaeza** [comment]
:+1:

Is this also happening in v8?

**Comment by gurneyalex** [comment]
:+1:

**Comment by fernandomr** [comment]
Please, can someone review this PR?
Thanks!

**Comment by pedrobaeza** [comment]
OK, as we have already 2 approvals and more than 5 days, I can merge. Anyways, @fernandomr, you can also make a review to tell if it's working on your side, and add another thumb up if affirmative.

**Comment by fernandomr** [comment]
It's working!
:+1:

**Pull request merged**
