### PR TITLE
[10.0] [IMP] account_financial_report_qweb - foreign currencies + dynamic reporting

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
superseed #407

### CODE REVIEW

**Review by jackjack82 — CHANGES_REQUESTED** [review]
I get an error doing the following:
1) activate multi-currency
2) create invoice
3) click "View" in Open Items report (the original currency is properly shown)
4) click on "Export" and get the following error

'OpenItemsXslx' object has no attribute 'workbook': (<type 'exceptions.AttributeError'>, AttributeError("'OpenItemsXslx' object has no attribute 'workbook'",), <traceback object at 0x7f1a99fc5200>)

Giacomo

**Review by jackjack82 — APPROVED** [review]
I tested the export xls from view and works, approved.

**Comment by pedrobaeza** [comment]
Can you squash a bit the commit history?

**Comment by HviorForgeFlow** [comment]
Done

**Pull request merged**
