### PR TITLE
[8.0] [account_financial_report_webkit_xls] add aged partner balance & aged open invoices xls

### PR DESCRIPTION
**Pull request by hbrunn**
#259 revisited

### CODE REVIEW

**Comment by hbrunn** [comment]
@luc-demeyer @StefanRijnhart @aschenkels-ictstudio I took the liberty to solve the conflicts in #259 and propose it here

**Comment by hbrunn** [comment]
if @luc-demeyer agrees, I'll squash all his commits

**Comment by luc-demeyer** [comment]
@hbrunn 
Thanks for this work. Lots of small syntax improvements and new functionality with the XLS export on open invoices.

I tested this Open Invoices XLS export but this doesn't work yet.

Issue1 : the import should be 

from openerp.addons.account_financial_report_webkit.report \
    .aged_open_invoices import AccountAgedOpenInvoicesWebkit

After this, the report is there, but the XLS export still doesn't work.
A quick code review showed a deviation from the mako logic in the XLS code.
E.g. _p.agged_lines_accounts is should become _p.aged_open_inv (cf. mako line 92).

**Review by StefanRijnhart — APPROVED** [review]

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
Retracting my approval as per luc's comments.

**Comment by hbrunn** [comment]
thanks, this is what you get when you want to finish something before Christmas vacation and don't read the code you use properly. Will do better, sorry for wasting your time

**Comment by StefanRijnhart** [comment]
@hbrunn have a great vacation!

**Comment by hbrunn** [comment]
@StefanRijnhart thank you. And when this document of shame is fixed and green, I can actually enjoy it ;-)

**Comment by hbrunn** [comment]
huh, no runbot?

**Comment by hbrunn** [comment]
@StefanRijnhart @luc-demeyer yay, green finally!

**Comment by luc-demeyer** [comment]
Great work. :+1 for merge.

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
