### PR TITLE
80 update account journal report xls

### PR DESCRIPTION
**Pull request by luc-demeyer**
- allow inherited module to extend the namespace for the xls template
- module documentation update

### CODE REVIEW

**Comment by gurneyalex** [comment]
My PR fixing the runbot and travis build on the 8.0 branch were recently merged. Can you rebase your PR?

**Comment by luc-demeyer** [comment]
@guewen 
I need help from one of the "OCA maintainer tools" gurus in order to greenify this PR:
The recent changes in the maintainer tools flag the use of "eval" which is good, but in some cases eval can be legitimate. 
We should be able to cope with such a situation.
I tried to fix the "W0123(eval-used)" error via the "noqa" but it doesn't seem to help (cf. account_journal_report_xls/report/nov_account_journal.py:218).
Is there a way to indicate a legitimate eval ?

**Comment by pedrobaeza** [comment]
Is this a dead branch and should we close it?

**Comment by luc-demeyer** [comment]
It's a very useful module and although the PR is red, the module works great and offers functionally that is currently not available in other V8.0 modules.
I'll greenify the PR later this week (the noqa should not be blocking any more).

**Comment by feketemihai** [comment]
@luc-demeyer Will you still work on this one?

**Comment by pedrobaeza** [comment]
This is conflicting and no answer, so I suppose this has been improved other way meanwhile, and thus I'm closing this.

**Pull request closed without merging**
