### PR TITLE
[FIX] account_tax_balance: tax from bank statements is not reported

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
When I assign an (inclusive) tax to a bank statement during reconciliation, the tax is not reported by account_tax_balance because all moves that include a line on a liquidity account are ignored by design.

It seems to me that this can be easily fixed by including all moves in the 'regular' computed fields except for 'refund' type moves.

@eLBati what do you think? Any reason that you excluded these move types in the first place?

**Comment by astirpe** [comment]
For the Dutch Vat Statement reports (eg.: module `l10n_nl_tax_declaration_reporting`) we definitely need this fix. Thanks @StefanRijnhart !

In case the authors of this module do not agree on this fix, there is no problem: the module `l10n_nl_tax_declaration_reporting`, or whatever module inherits this one, could extend method `def get_target_type_list()` and fix it properly to retrieve the needed data.

For me is a :+1: to have this

**Comment by jvOrsouw** [comment]
I'm trying out this module. I agree with removing the constraint on 'internal type = payable , receivable'. It gives an accurate presentation of the taxes posted in the system. 

👍

**Review by eLBati — APPROVED** [review]
I am OK with this.

I would like to know what @antespi thinks, as he introduced ```get_target_type_list``` at https://github.com/OCA/account-financial-reporting/commit/cfb0b1322f3dc8b258785261002e5f6b79179606

**Comment by StefanRijnhart** [comment]
@elBati thanks for the clarification. It is a regression due to the redesign then.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
OK, seems correct also for us, but please change version number.

**Comment by StefanRijnhart** [comment]
@pedrobaeza done

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Merged and cherry-pick for v9.

**Comment by pedrobaeza** [comment]
Although the PR doesn't have problems, when merging it test have failed: https://travis-ci.org/OCA/account-financial-reporting/jobs/212446472

**Comment by StefanRijnhart** [comment]
@pedrobaeza So in 9.0, the tax line is still created automatically https://github.com/OCA/account-financial-reporting/pull/286

**Comment by StefanRijnhart** [comment]
Indeed, the default behaviour of applying taxes was changed from 9.0 to 10.0: https://github.com/odoo/odoo/commit/89cbef8540ab0#diff-dd671a54296b170ea1393dca1a5f7798L995

**Pull request merged**
