### PR TITLE
[17.0][MIG] partner_statement: Migration to 17.0

### PR DESCRIPTION
**Pull request by ellbristow**
Only notable changes for 17.0 are the standard attrs changes and the simplified res.config.settings views. Everything else appears to work as it did in 16.0

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by MiquelRForgeFlow** [comment]
Please, squash last two commits to the migration commit. In fact, migration commit, due to [guidelines](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0), has to be `[MIG] <module>: Migration to 17.0`.

**Comment by ellbristow** [comment]
Commits squashed

**Review by theangryangel — APPROVED** [review]
LGTM. Functionally tested

**Review by AaronHForgeFlow — APPROVED** [review]
Code LGTM

**Pull request merged**
