### PR TITLE
[13.0][MIG] mis_template_financial_report: Migration to 13.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 13.0 (Backport from 14.0)

Please @chienandalu and @pedrobaeza can you review it?

@Tecnativa TT36042

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Review by rafaelbn — APPROVED** [review]
Super 👍 thank!

**Comment by HaraldPanten** [comment]
Hey @pedrobaeza @victoralmau you are planning to [MIG] this to V15, aren't you?

THX!

**Comment by pedrobaeza** [comment]
Not for now

**Pull request merged**
