### PR TITLE
[10.0][mis_builder] Adds multi bar Chart display choice

### PR DESCRIPTION
**Pull request by Martronic-SA**
in Mis report instance I've added a field to chosse between standard table or bar chart display.
It's using default odoo libraries nv.

TODO : add line chart, pie chart, maybe add a display options to each KPI so it's possible to mix different types of charts together.

### CODE REVIEW

**Comment by sbidoul** [comment]
Interesting. Can you paste a screenshot?

**Comment by Martronic-SA** [comment]
here a sample (amounts on left are partially hidden for confidentiality)

**Comment by Martronic-SA** [comment]
Now the line chart 👍

**Comment by sbidoul** [comment]
Nice. Not sure these chart are generic enough, though. Perhaps this should go in an extension module.

Have you considered adding a column displaying [sparklines](https://en.wikipedia.org/wiki/Sparkline) with data of other selected columns?

**Comment by Martronic-SA** [comment]
Added multichart support:
Sample below comparision Revenu/Expenses/EBITA 2016 and 2017 per month and cumulative on year

**Comment by adrienpeiffer** [comment]
As MIS Builder module hase been moved in https://github.com/OCA/mis-builder, I'll close this one

**Pull request closed without merging**
