### PR TITLE
[10.0][IMP] add salesperson to account_financial_report_qweb

### PR DESCRIPTION
**Pull request by robyf70**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You are mixing a sales concept with financial one, so this is a nonsense IMO. 👎

**Comment by robyf70** [comment]
@pedrobaeza I might agree with you, but how can I give at an agent/salesman a list of due payments?

**Comment by pedrobaeza** [comment]
You have the module account_credit_control for that, with the possibility of assigning a responsible for each due.

**Comment by robyf70** [comment]
ahh! will give a look! is there also a similar report?

**Comment by robyf70** [comment]
@pedrobaeza Not sure if I've understood the module you told me, but looks like I cannot give an agent a report of all due payments. The account_credit_control seems doing other automatized checks or I'm missing something?

**Comment by pedrobaeza** [comment]
You can automate the responsible to be the "agent" and split the information.

**Comment by robyf70** [comment]
... which is fine and useful for that purpose. But still, We don't have a report where we can filter all due payments by agent/salesperson.

**Comment by pedrobaeza** [comment]
Then make it a separate report, but this can't be integrated in main one.

**Comment by robyf70** [comment]
Ok! will do that

**Pull request closed without merging**
