### PR TITLE
in general ledger report, the sum is done on wrong column

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
before :

image

after :

image

The regression was introduced with the PR #45 

I don't know how it is possible to add automated test on xls report, but it can be a good idea...

### CODE REVIEW

**Comment by laetitia-gangloff** [comment]
And there is also a problem with initial balance :

image

**Comment by vrenaville** [comment]
Thanks for this fix :+1:

**Comment by mdietrichc2c** [comment]
:+1: thanks for the fix

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
