### PR TITLE
[13.0][MIG] account_bank_reconciliation_summary_xlsx

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
Looks good to me
Functional test and code review.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
It would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
@JoanSForgeFlow  and @JordiBForgeFlow it would be nice if you add reviews here.

**Review by rafaelbn — APPROVED** [review]
LGTM 👍

**Pull request merged**
