### PR TITLE
mis_builder: better layout of mis report settings form on small screens

### PR DESCRIPTION
**Pull request by sbidoul**
image

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
:+1: (Functionnal test & Code review)

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by sbidoul** [comment]
I also improved the layout of the template form so it's not overflowing the sheet anymore.

image

**Comment by adrienpeiffer** [comment]
@sbidoul it seems that the form template still overlaps the sheet. But I don't know if this problem can be solved. So :+1:

**Comment by sbidoul** [comment]
@adrienpeiffer there is not much more we can do indeed. `web_sheet_full_width` helps. And when we'll add more features (styles, sub-kpis) we'll create popups to edit KPI's instead of having an editable list.

But that's for the future. In the meantime, the screen is nicer with this PR anyway.

**Comment by lepistone** [comment]
👍 thanks!

**Pull request merged**
