### PR TITLE
8.0 add intrastat v3 fix invoice onchange product

### PR DESCRIPTION
**Pull request by damdam-s**
superseed https://github.com/OCA/account-financial-reporting/pull/80

### CODE REVIEW

**Comment by damdam-s** [comment]
@alexis-via @StefanRijnhart @bealdav @luc-demeyer Fix for your PR #80 
clean travis and runbot.
I can give you push access to this branch if you want the coverage to be green.

**Comment by alexis-via** [comment]
@damdam-s You should push to my branch, not directly here. So we should cancel this PR.

**Comment by damdam-s** [comment]
@alexis-via no problem. Can you tell me on which branch I have to push ?

**Comment by alexis-via** [comment]
This one: https://github.com/akretion/account-financial-reporting/commits/8.0-add-intrastat-v3

**Comment by alexis-via** [comment]
@damdam-s Could you close this PR, to avoid confusion ?

**Comment by hparfr** [comment]
Is this PR still relevant ? 
https://github.com/OCA/intrastat

**Pull request closed without merging**
