### PR TITLE
[Fix] #57 Fixed accented characters in report names

### PR DESCRIPTION
**Pull request by martini97**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This fix is not valid, as it replaces the accentuated characters. You need to set the correct language on the terminal.

**Comment by martini97** [comment]
As @alexis-via said, using arguments in the command line to fix this is dirty
"""
@sbidoul Do you consider the solution above as the "real" fix, or as a sort of hack/workaround ?

When I read this comment in the code:
https://github.com/OCA/account-financial-reporting/blob/8.0/account_financial_report_webkit/report/webkit_parser_header_fix.py#L51

it confirms what I think: it's really dirty to use arguments to a command line to pass this kind of information with accentuated characters.
"""

**Comment by sbidoul** [comment]
@martini97 I'm not sure everyone talks about the same thing when using the word "command line argument" here.

What is dirty is using arguments to pass such long textual information such as header and footer, I agree. However, this is due to the way wkhtmltopdf works, there is now way around it, as far as I know. So we have to live with.

Configuring the environment variable to have Odoo run in a proper unicode environment is clean and robust. IMO, it is more robust than trying to fiddle and convert encodings in the code.

That's why I'm :-1: for this PR for now.

**Comment by ovnicraft** [comment]
Close this ?

**Pull request closed without merging**
