### PR TITLE
silence warnings

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
I'm still very uneasy with such brutal silencing of import errors. Things will become hard to debug when a real error will lurk in there.

BTW, what do you think about this proposal: https://github.com/odoo/odoo/issues/7507#issuecomment-136434162

**Comment by lepistone** [comment]
@sbidoul I'm not happy of silencing errors of course, but I don't know any other way that works today.

**Comment by feketemihai** [comment]
@lepistone I will close one since no activity for a long time. Please reopen it if still need it.

**Comment by lepistone** [comment]
Absolutely @feketemihai, thanks!

**Pull request closed without merging**
