### PR TITLE
translation

### PR DESCRIPTION
**Pull request by BT-ojossen**
added translation file for language de

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1: Technically

**Comment by pedrobaeza** [comment]
Technically :+1: 

@osguard, can you check it?

**Comment by OSguard** [comment]
"pdf or xls" is removed in the translation of the help text.
But from the rest it looks fine.

**Comment by yvaucher** [comment]
As the last commit message is "test" I set this as work in progress

**Comment by BT-ojossen** [comment]
closed because duplicated with #121

**Comment by feketemihai** [comment]
@BT-ojossen I will close one since no activity for a long time. Please reopen it if still need it.

**Pull request closed without merging**
