### PR TITLE
[FIX] lints

### PR DESCRIPTION
**Pull request by hbrunn**
remaining lints are fixed in #352

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Wow, such a big change! It's not only fixing pylint, but converting to new API.

**Review by melroy89 — APPROVED** [review]
merge?

**Review by astirpe — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
rebase?

**Comment by hbrunn** [comment]
let's not wait until this conflicts again

**Comment by pedrobaeza** [comment]
@hbrunn can we avoid the merge operation that mixes all the commits and make a rebase operation instead?

**Comment by hbrunn** [comment]
this was my first time using github's conflict resolution feature, does not what we want. But I see the 8 branch is green meanwhile anyways, to I just close this

**Comment by pedrobaeza** [comment]
Maybe that's the reason of the conflicts...

**Pull request closed without merging**
