### PR TITLE
Update wkhtmltopdf download url

### LINKED ISSUE #94: use updated URL for wkhtmltopdf downloads
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:
- .travis.yml

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

### PR DESCRIPTION
**Pull request by gurneyalex**
don't use sudo to run wget.

closes #94

### CODE REVIEW

**Comment by veloutin** [comment]
:+1:

**Comment by gurneyalex** [comment]
as for #96, fast tracking is welcome as all PR on the 7.0 branches are currently failing.

**Comment by tafaRU** [comment]
:+1:

**Comment by gurneyalex** [comment]
red runbot should be fixed by #98

**Comment by lepistone** [comment]
:+1:

**Pull request merged**
