### PR TITLE
[14.0][MIG] partner_statement: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Superseed: https://github.com/OCA/account-financial-reporting/pull/762

Migration to 14.0

Please @joao-p-marques and @CarlosRoca13 can you review it?

@Tecnativa TT30008

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
Seems good :+1: Code review

**Comment by MiquelRForgeFlow** [comment]
Thanks. Please, cherry-pick https://github.com/OCA/account-financial-reporting/pull/804

**Review by joao-p-marques — APPROVED** [review]
LGTM too :+1: 

Code review

**Review by dsolanki-initos — APPROVED** [review]
Code review and test LGTM

**Pull request merged**
