### PR TITLE
[14.0][FIX] partner_statement: avoid showing lines with 0.00001 open amounts

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
:)

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@gdgellatly @JordiBForgeFlow @AaronHForgeFlow @ChrisOForgeFlow

**Comment by MiquelRForgeFlow** [comment]
@ChrisOForgeFlow

**Review by AaronHForgeFlow — APPROVED** [review]
Code LGTM. The name of the method would be _check_line_significant_residual, or something similar

**Comment by MiquelRForgeFlow** [comment]
@AaronHForgeFlow no, because other custom extensions could add other additional checks in that method. I wanted a generic name on purpose. The method only serves to check if the line should be shown or not. It could also be named `_check_show_line` or similar...

**Comment by gdgellatly** [comment]
> @AaronHForgeFlow no, because other custom extensions could add other additional checks in that method. I wanted a generic name on purpose. The method only serves to check if the line should be shown or not. It could also be named `_check_show_line` or similar...

Hi,

I'm OK with this PR. But I think it could be improved. check_line_is_correct either appends or does not append. It is quite limited and restrictive and doesn't really have much of an extensibility use case. I think if we really want to make extensible then we should really do something more like

`line['currency'].extend(self._prepare_currency_line(line, currency_id))`

then 
```
def _prepare_currency_line(self, line, currency_id)
  if <wrong>:
    return []
  return line
```
which allows
```
def _prepare_currency_line(self, line, currency_id):
  res = super()
  if res and <almost right>:
    res['foo'] = 'bar'
  return res
```

**Comment by MiquelRForgeFlow** [comment]
@gdgellatly done

**Review by gdgellatly — APPROVED** [review]
LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Forward-port in https://github.com/OCA/account-financial-reporting/pull/936.

**Pull request merged**
