### PR TITLE
[FIX] account_financial_report_webkit_xls: Show currency of invoice independent of the account currency.

### PR DESCRIPTION
**Pull request by ghost**
Now it is consistent with the regular webkit report (https://github.com/OCA/account-financial-reporting/blob/7.0/account_financial_report_webkit/report/templates/open_invoices_inclusion.mako.html#L108)

### CODE REVIEW

**Comment by ghost** [comment]
@pedrobaeza i know this is pretty old but is there a chance on getting this PR merged?

**Comment by pedrobaeza** [comment]
Well, if you review a couple of other PRs in this repo, for sure there will be people willing to review yours, me included :wink:

**Comment by pedrobaeza** [comment]
Check Travis result

**Comment by ghost** [comment]
thanks for the hint @pedrobaeza 
and well said: I hope i find some time to contribute

**Pull request closed without merging**
